"""
RAPP Agent Template
Generated by rapp-claude-skills

This template provides the base structure for RAPP-compatible agents.
Customize the perform() method with your agent's logic.
"""

from agents.basic_agent import BasicAgent
import logging

class {AGENT_NAME}Agent(BasicAgent):
    """
    {AGENT_DESCRIPTION}

    Generated via RAPP Pattern methodology.
    """

    def __init__(self):
        self.name = '{AGENT_NAME}'
        self.metadata = {
            "name": self.name,
            "description": "{AGENT_DESCRIPTION}",
            "parameters": {
                "type": "object",
                "properties": {
                    # Define your agent's input parameters here
                    "input": {
                        "type": "string",
                        "description": "The input to process"
                    }
                },
                "required": ["input"]
            }
        }
        super().__init__(self.name, self.metadata)

    def perform(self, **kwargs) -> str:
        """
        Execute the agent's main logic.

        Args:
            **kwargs: Parameters matching the metadata schema

        Returns:
            str: The agent's response
        """
        try:
            # Extract parameters
            input_data = kwargs.get('input', '')

            # Your agent logic here
            result = self._process(input_data)

            return result

        except Exception as e:
            logging.error(f"{self.name} error: {e}")
            return f"Error processing request: {str(e)}"

    def _process(self, input_data: str) -> str:
        """
        Internal processing logic.
        Override this method with your implementation.
        """
        # TODO: Implement your agent's core functionality
        return f"Processed: {input_data}"


# For testing
if __name__ == "__main__":
    agent = {AGENT_NAME}Agent()
    print(f"Agent: {agent.name}")
    print(f"Metadata: {agent.metadata}")

    # Test execution
    result = agent.perform(input="test input")
    print(f"Result: {result}")
