http_port 3128
pid_filename /tmp/squid.pid
cache_effective_user proxy
cache_effective_group proxy
cache_mem 8 MB
cache deny all
http_access deny all
access_log stdio:/dev/stdout
cache_log /dev/stderr
cache_store_log none
logfile_rotate 0
shutdown_lifetime 1 seconds
coredump_dir /tmp
