title: The RAPP Programming Language
description: A tutorial, programming workbook, and reference manual for verifiable agents
baseurl: /rapp-1
url: https://kody-w.github.io
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
exclude:
  - .gitignore
  - book/build-pdf.sh
  - book/test-docs.sh
  - book/test-interactive.py
  - book/test-pdf.py
  - estate
