#!/usr/bin/env python3
"""Repository invariants and byte-for-byte deterministic build check."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from rapp_base.build import build
from rapp_base.errors import RappError
from rapp_base.manifest import load_manifest
from rapp_base.write_control import WriteControlError, validate_control_file

_ACTION_RE = re.compile(r"^\s*uses:\s*[^@\s]+@([0-9a-f]{40})(?:\s+#.*)?$")


def _duplicates(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate key {key}")
        result[key] = value
    return result


def _reject_constant(value):
    raise ValueError(f"non-finite number {value}")


def _snapshot(root: Path) -> dict[str, str]:
    paths = [root / "registry.json"]
    for directory in ("api", "versions"):
        paths.extend(path for path in (root / directory).rglob("*") if path.is_file())
    return {
        path.relative_to(root).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(paths)
    }


def _reject_symlinks(root: Path) -> None:
    for current, directories, files in os.walk(root, followlinks=False):
        current_path = Path(current)
        if current_path == root:
            directories[:] = [name for name in directories if name != ".git"]
        for name in [*directories, *files]:
            path = current_path / name
            if path.is_symlink():
                raise RappError(
                    "symlink",
                    f"repository symlinks are forbidden: {path.relative_to(root)}",
                )


def check_control_document(root: Path) -> None:
    try:
        validate_control_file(root, require_canonical=True)
    except WriteControlError as exc:
        raise RappError("invalid_write_control", str(exc)) from exc


def check(root: Path) -> None:
    if sys.version_info < (3, 12):
        raise RappError("python_version", "Python 3.12 or newer is required")
    _reject_symlinks(root)
    check_control_document(root)
    manifest = load_manifest(root)
    repository = manifest["repository"]
    schema_id_base = (
        f"https://{quote(repository['owner'], safe='')}.github.io/"
        f"{quote(repository['name'], safe='')}/schemas/"
    )
    before = _snapshot(root)
    build(root, manifest, write=False)
    after = _snapshot(root)
    if before != after:
        raise RappError("mutating_check", "read-only validation changed generated bytes")

    for scratch in (".work", ".pages", ".scale-work", ".test-work"):
        if (root / scratch).exists():
            raise RappError("scratch_directory", f"scratch directory remains: {scratch}")
    excluded = {".git"}
    for path in root.rglob("*"):
        relative = path.relative_to(root)
        if any(part in excluded for part in relative.parts):
            continue
        if path.name == "__pycache__" or path.suffix in {".pyc", ".pyo"}:
            raise RappError("cache_file", f"cache file exists: {relative}")
        if path.name.endswith(".new") or path.name.endswith(".stage"):
            raise RappError("staging_file", f"staging file exists: {relative}")
        if path.suffix == ".py":
            compile(path.read_text(encoding="utf-8"), str(relative), "exec")
        if path.suffix == ".json":
            try:
                value = json.loads(
                    path.read_text(encoding="utf-8"),
                    object_pairs_hook=_duplicates,
                    parse_constant=_reject_constant,
                )
            except (OSError, UnicodeError, ValueError, json.JSONDecodeError) as exc:
                raise RappError("invalid_json_file", f"invalid JSON: {relative}") from exc
            if relative.parts[:2] == ("api", "v1") and (
                not isinstance(value, dict) or "schema" not in value
            ):
                raise RappError("missing_schema", f"API document lacks schema: {relative}")
            if relative.parts[:1] == ("schemas",):
                if (
                    not isinstance(value, dict)
                    or value.get("$schema")
                    != "https://json-schema.org/draft/2020-12/schema"
                    or not isinstance(value.get("$id"), str)
                    or not value["$id"].startswith(schema_id_base)
                ):
                    raise RappError(
                        "invalid_json_schema",
                        f"JSON Schema metadata is invalid: {relative}",
                    )
            elif isinstance(value, dict) and "$schema" in value:
                raise RappError(
                    "legacy_discriminator",
                    f"protocol document uses $schema instead of schema: {relative}",
                )

    placeholders = (
        "rapp-base" + ".invalid",
        "YOUR" + "_",
        "OWNER" + "/rapp-base",
    )
    for path in root.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        if path.suffix.lower() not in {
            ".py",
            ".js",
            ".mjs",
            ".json",
            ".md",
            ".txt",
            ".html",
            ".yml",
            ".yaml",
        }:
            continue
        text = path.read_text(encoding="utf-8")
        if any(marker in text for marker in placeholders):
            raise RappError("placeholder", f"placeholder remains: {path.relative_to(root)}")

    for workflow in sorted((root / ".github" / "workflows").glob("*.yml")):
        text = workflow.read_text(encoding="utf-8")
        if "pull_request_target" in text:
            raise RappError("unsafe_workflow", f"{workflow.name} uses pull_request_target")
        if "${{ github.event.issue.body" in text or "${{ github.event.issue.title" in text:
            raise RappError("unsafe_workflow", f"{workflow.name} interpolates Issue text")
        for line in text.splitlines():
            if "uses:" in line and _ACTION_RE.fullmatch(line) is None:
                raise RappError(
                    "unpinned_action", f"{workflow.name} has an unpinned action: {line.strip()}"
                )

    explorer = (root / "explorer.js").read_text(encoding="utf-8")
    forbidden_dom = (".innerHTML", "insertAdjacentHTML", "document.write")
    if any(token in explorer for token in forbidden_dom):
        raise RappError("unsafe_dom", "explorer contains an unsafe HTML sink")
    if (root / "package.json").exists():
        raise RappError("dependency_manifest", "root package.json is not needed")
    sdk_package = json.loads((root / "sdk" / "package.json").read_text(encoding="utf-8"))
    if any(
        key in sdk_package
        for key in (
            "dependencies",
            "devDependencies",
            "optionalDependencies",
            "peerDependencies",
        )
    ):
        raise RappError("runtime_dependency", "SDK package must remain dependency-free")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    try:
        check(args.root.resolve())
    except (OSError, RappError) as exc:
        message = exc.message if isinstance(exc, RappError) else str(exc)
        print(f"check failed: {message}", file=sys.stderr)
        return 1
    print("repository checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
