"""
bookfactoryagent.py — the deployable BookFactory singleton.

ONE sacred agent.py file containing the entire converged book-writing
pipeline. Drop it into any RAPP brainstem's agents/ directory and it works.

This file is generated by tools/build-bookfactoryagent.py from the
multi-file source under agents/. The multi-file form is editable and
iterable (the double-jump loop runs against it). This singleton is the
SHIP-TIME artifact: no sibling-import dependencies, no helper modules,
no repo layout assumptions. Just BasicAgent + an LLM key in the
environment, and the public BookFactory.perform(source, ...) → chapter.

Inlined personas (sacred SOULs preserved verbatim):
  - Writer
  - Editor (composite of 5 specialists: strip-scaffolding, cutweak,
    restructure, factcheck, voicecheck)
  - CEO (composite of 2 specialists: risk, decision)
  - Publisher
  - Reviewer

Public entrypoint: the BookFactory class. Every internal class is
prefixed with _Internal to keep them out of the brainstem's automatic
*Agent discovery — only BookFactory is exposed as a hot-loadable agent.

Generated from:
  - agents/persona_writer_agent.py
  - agents/editor_strip_scaffolding_agent.py
  - agents/editor_cutweak_agent.py
  - agents/editor_restructure_agent.py
  - agents/editor_factcheck_agent.py
  - agents/editor_voicecheck_agent.py
  - agents/ceo_risk_agent.py
  - agents/ceo_decision_agent.py
  - agents/persona_publisher_agent.py
  - agents/persona_reviewer_agent.py
  - agents/persona_editor_agent.py
  - agents/persona_ceo_agent.py
  - agents/book_factory_agent.py
"""

from agents.basic_agent import BasicAgent
import json
import os
import urllib.request
import urllib.error


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/book-factory-singleton",
    "tier": "core",
    "trust": "community",
    "version": "0.3.0",
    "tags": ["composite", "creative-pipeline", "twin-stack", "singleton"],
    "delegates_to_inlined": [
        "@rapp/persona-writer",
        "@rapp/persona-editor",
        "@rapp/editor-strip-scaffolding",
        "@rapp/editor-cutweak",
        "@rapp/editor-restructure",
        "@rapp/editor-factcheck",
        "@rapp/editor-voicecheck",
        "@rapp/persona-ceo",
        "@rapp/ceo-risk",
        "@rapp/ceo-decision",
        "@rapp/persona-publisher",
        "@rapp/persona-reviewer",
    ],
    "example_call": {"args": {"source": "raw notes...", "chapter_title": "Chapter 1"}},
}


# ─── SOUL constants (verbatim from each leaf agent.py) ─────────────────

_SOUL_PERSONA_WRITER = """You are a senior nonfiction writer. You take raw source material and turn it
into prose that respects the reader's time. You favor concrete examples over
abstractions. You write in scenes, not summaries. You never pad. If the source
has gaps, you say so rather than fabricate.

CRITICAL for technical writing: when the source material contains code blocks
(text inside ```...``` fences) or specific filenames, function names, or API
shapes, INCLUDE THEM VERBATIM in your draft. Code is evidence. A claim about
how a system works lands twice as hard when the reader can see the actual
function being discussed. Use 1-3 fenced code blocks per draft when source
material supports it. Quote real filenames (`agents/foo_agent.py`) and real
identifiers (`run_pipeline`) instead of paraphrasing them.

You also output clean publishable prose — no '## Outline' scaffolding at the
top, no 'TODO' placeholders, no draft-state labels. Write as if your draft
will be published as-is."""

_SOUL_EDITOR_STRIP_SCAFFOLDING = """You are a meta-artifact stripper. You read prose that may have been
written by a draft-and-outline workflow, and you remove anything that's
scaffolding rather than content:

- Lines like '## Outline' followed by a bullet list of sections (the Writer
  often leaves these in by mistake)
- Empty 'TODO' / 'PLACEHOLDER' / 'FIXME' headers
- Duplicate H1 titles (sometimes the Writer puts both a YAML title field AND
  a markdown # title — keep only the markdown one)
- Working notes in square brackets like '[expand here]' or '[see source]'
- ALL-CAPS section labels that are clearly draft-state ('NOTE TO SELF', 'DRAFT')
- Trailing 'sign-off as @writer' instructions that leaked from the prompt

You preserve everything else verbatim — voice, structure, code blocks,
prose, formatting. You output ONLY the cleaned text, nothing else.

CRITICAL: Never cut fenced code blocks. Never cut real markdown headers
that are part of the document's structure (the kind a published version
would have). Cut only the pre-publication scaffolding."""

_SOUL_EDITOR_CUTWEAK = """You are a 'cut the weakest 20%' editor pass. You read prose and
return the same prose with the weakest paragraphs removed. You preserve the
writer's voice. You do not add new content. You output ONLY the cut prose,
nothing else.

CRITICAL: Fenced code blocks (```...```) are EVIDENCE, not prose. Never cut
a code block. Never abbreviate one. Never replace one with a description of
what it shows. If a paragraph is weak, cut the paragraph; if a code block
sits next to weak prose, keep the code block, cut the prose around it.
Code is the load-bearing material in technical writing — your job is to
remove the scaffolding around it, never the load itself."""

_SOUL_EDITOR_RESTRUCTURE = """You are a structural editor. You read prose and consolidate
repetitive middle sections — passages where the same point is restated
2-3 times in slightly different words. This is a common failure mode in
long-form drafts: the writer makes a claim in paragraph 3, restates it in
paragraph 5, restates it again in paragraph 7. Each restatement feels like
emphasis but is actually drag.

Your job: identify those repetitions, KEEP the strongest single statement
of the idea, DELETE the others. You do not rewrite. You do not add. You
output the same draft minus the redundant restatements.

You preserve voice. You preserve code blocks (never cut a fenced code
block). You preserve real structural progression — when a later paragraph
sharpens or extends an earlier point, that is NOT repetition; keep both.
Cut only when a paragraph could be deleted with no loss of information,
because its information is already on the page elsewhere.

Output ONLY the restructured prose, nothing else."""

_SOUL_EDITOR_FACTCHECK = """You are a fact-check pass for an editor. You read prose and surface
claims that need a source. You do NOT rewrite. You list 2-5 specific claims
verbatim from the text along with what kind of source would prove or disprove each."""

_SOUL_EDITOR_VOICECHECK = """You are a voice-continuity check. You read prose and identify
sentences or phrases that drift away from the writer's natural voice (toward
generic-essayese, toward marketing-speak, toward AI-flavored hedging).
You quote the offending lines and say what voice they drifted into."""

_SOUL_CEO_RISK = """You assess partner-conversation risk for content about to ship.
You think about what estate attorneys, family offices, investors, and the
press will hear (vs what was meant). You list the 1-3 risks that would
actually matter in a real meeting, not generic legal CYA."""

_SOUL_CEO_DECISION = """You make a CEO ship decision on content. You give exactly two things:
(1) ship as-is / ship with edits / hold; (2) the ONE line you want changed
before it goes out. You don't critique line-by-line — you make a call."""

_SOUL_PERSONA_PUBLISHER = """You are an indie-press publisher. You ship artifacts, not opinions.
You take edited prose plus a CEO note, apply the requested change, and produce
a publication-ready markdown file with proper YAML frontmatter (title, author,
date, chapter_number). You output nothing but the markdown."""

_SOUL_PERSONA_REVIEWER = """You are a smart reader who didn't build this thing. You score what
works and what bored you. You name the strongest line. You decide whether
you'd keep reading. You're nice but honest."""


# ─── Internal persona classes (prefixed to hide from *Agent discovery) ─

class _InternalPersonaWriter(BasicAgent):
    def __init__(self):
        self.name = "Writer"
        self.metadata = {
            "name": self.name,
            "description": "The Writer persona. Takes source material, returns chapter-style prose.",
            "parameters": {
                "type": "object",
                "properties": {
                    "input": {"type": "string", "description": "Raw source material"},
                    "chapter_title": {"type": "string", "description": "Working title"},
                    "max_words": {"type": "integer", "description": "Word cap (default 800)"},
                },
                "required": ["input"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", chapter_title="Untitled", max_words=800, **kwargs):
        prompt = (
            f"Source material:\n\n--- SOURCE ---\n{input}\n--- END ---\n\n"
            f"Outline a chapter titled '{chapter_title}'. Then draft it. Lead with one "
            f"concrete scene from the source. Plain prose. Single H1. Under {max_words} words. "
            f"Sign off as @writer."
        )
        return _llm_call(_SOUL_PERSONA_WRITER, prompt)

class _InternalEditorStripScaffolding(BasicAgent):
    def __init__(self):
        self.name = "EditorStripScaffolding"
        self.metadata = {
            "name": self.name,
            "description": "Strips outline headers, TODO markers, draft-state labels, "
                           "and other meta-artifacts the Writer leaked into the draft.",
            "parameters": {"type": "object",
                "properties": {"input": {"type": "string", "description": "Draft prose"}},
                "required": ["input"]},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        return _llm_call(_SOUL_EDITOR_STRIP_SCAFFOLDING,
            f"Draft to strip:\n{input}\n\nReturn the cleaned draft. Output ONLY "
            "the cleaned text. Preserve voice, code, real headers. Cut only "
            "scaffolding artifacts.")

class _InternalEditorCutweak(BasicAgent):
    def __init__(self):
        self.name = "EditorCutweak"
        self.metadata = {
            "name": self.name,
            "description": "Returns the same prose with the weakest 20% cut.",
            "parameters": {"type": "object",
                "properties": {"input": {"type": "string", "description": "Draft prose"}},
                "required": ["input"]},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        return _llm_call(_SOUL_EDITOR_CUTWEAK,
            f"Draft to cut:\n{input}\n\nReturn the same draft with the weakest "
            "20% removed. Output only the cut prose. No commentary.")

class _InternalEditorRestructure(BasicAgent):
    def __init__(self):
        self.name = "EditorRestructure"
        self.metadata = {
            "name": self.name,
            "description": "Consolidates repetitive middle sections — keeps the strongest "
                           "statement of each idea, cuts the restatements.",
            "parameters": {"type": "object",
                "properties": {"input": {"type": "string", "description": "Draft prose"}},
                "required": ["input"]},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        return _llm_call(_SOUL_EDITOR_RESTRUCTURE,
            f"Draft to restructure:\n{input}\n\nReturn the same draft with redundant "
            "restatements consolidated. Keep the strongest single statement of each "
            "idea. Cut the rest. Output ONLY the restructured prose.")

class _InternalEditorFactcheck(BasicAgent):
    def __init__(self):
        self.name = "EditorFactcheck"
        self.metadata = {
            "name": self.name,
            "description": "Flags claims in a draft that need sourcing.",
            "parameters": {"type": "object",
                "properties": {"input": {"type": "string", "description": "Draft prose"}},
                "required": ["input"]},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        return _llm_call(_SOUL_EDITOR_FACTCHECK,
            f"Draft to fact-check:\n{input}\n\nList 2-5 claims that need sourcing. "
            "For each: quote the claim, then say what source would settle it.")

class _InternalEditorVoicecheck(BasicAgent):
    def __init__(self):
        self.name = "EditorVoicecheck"
        self.metadata = {
            "name": self.name,
            "description": "Flags voice drift in a draft.",
            "parameters": {"type": "object",
                "properties": {"input": {"type": "string", "description": "Draft prose"}},
                "required": ["input"]},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        return _llm_call(_SOUL_EDITOR_VOICECHECK,
            f"Draft to voice-check:\n{input}\n\nList 0-3 lines where the voice "
            "drifts. Quote each line, name the voice it drifted into.")

class _InternalCEORisk(BasicAgent):
    def __init__(self):
        self.name = "CEORisk"
        self.metadata = {
            "name": self.name,
            "description": "Lists partner-conversation risks for content about to ship.",
            "parameters": {"type": "object",
                "properties": {"input": {"type": "string", "description": "Content under review"}},
                "required": ["input"]},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        return _llm_call(_SOUL_CEO_RISK,
            f"Content about to ship:\n{input}\n\nList 1-3 partner-conversation "
            "risks that would actually matter in a real meeting.")

class _InternalCEODecision(BasicAgent):
    def __init__(self):
        self.name = "CEODecision"
        self.metadata = {
            "name": self.name,
            "description": "CEO ship decision: as-is / edits / hold + the one line to change.",
            "parameters": {"type": "object",
                "properties": {"input": {"type": "string", "description": "Content under review"}},
                "required": ["input"]},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        return _llm_call(_SOUL_CEO_DECISION,
            f"Content under review:\n{input}\n\nReply with exactly two things:\n"
            "(1) Decision: ship as-is / ship with edits / hold\n"
            "(2) The ONE line you want changed before it goes out (quote it).")

class _InternalPersonaPublisher(BasicAgent):
    def __init__(self):
        self.name = "Publisher"
        self.metadata = {
            "name": self.name,
            "description": "The Publisher persona. Assembles publication-ready markdown.",
            "parameters": {
                "type": "object",
                "properties": {
                    "input":    {"type": "string", "description": "Edited content"},
                    "ceo_note": {"type": "string", "description": "CEO's review note"},
                    "title":    {"type": "string", "description": "Final title"},
                    "author":   {"type": "string", "description": "Author byline"},
                },
                "required": ["input"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", ceo_note="", title="Untitled",
                author="Unknown", **kwargs):
        prompt = (
            f"Edited prose:\n--- EDITED ---\n{input}\n--- END ---\n\n"
            f"CEO note:\n--- CEO ---\n{ceo_note}\n--- END ---\n\n"
            f"Apply the CEO's requested change. Output ONLY the final chapter as one "
            f"publication-ready markdown file. Use YAML frontmatter with: "
            f"title=\"{title}\", author=\"{author}\", date today, chapter_number=1. "
            f"No commentary, no explanation, no preamble — JUST the markdown file."
        )
        return _llm_call(_SOUL_PERSONA_PUBLISHER, prompt)

class _InternalPersonaReviewer(BasicAgent):
    def __init__(self):
        self.name = "Reviewer"
        self.metadata = {
            "name": self.name,
            "description": "The Reviewer persona. Reads cold, scores 1-5, names strongest line.",
            "parameters": {"type": "object",
                "properties": {"input": {"type": "string", "description": "Final content"}},
                "required": ["input"]},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        return _llm_call(_SOUL_PERSONA_REVIEWER,
            f"Final content:\n{input}\n\nIn 3 short bullets:\n"
            "(1) score 1-5\n(2) strongest line in the piece\n"
            "(3) would you keep reading the next chapter? Why or why not?")


# ─── Internal composite classes ────────────────────────────────────────

class _InternalPersonaEditor(BasicAgent):
    def __init__(self):
        self.name = "Editor"
        self.metadata = {
            "name": self.name,
            "description": "The Editor persona. Strips scaffolding → cuts weak prose "
                           "(preserving code) → restructures repetitive middles, then "
                           "runs factcheck + voicecheck for the editor's note.",
            "parameters": {
                "type": "object",
                "properties": {"input": {"type": "string", "description": "Writer's draft"}},
                "required": ["input"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        # Sequential transformations on the prose itself
        stripped     = _InternalEditorStripScaffolding().perform(input=input)
        cut          = _InternalEditorCutweak().perform(input=stripped)
        restructured = _InternalEditorRestructure().perform(input=cut)

        # Parallel-in-spirit checks against the original draft (so the
        # checks see what was claimed before any cutting happened)
        facts = _InternalEditorFactcheck().perform(input=input)
        voice = _InternalEditorVoicecheck().perform(input=input)

        return (
            f"{restructured}\n"
            f"---\n"
            f"**Editor's note**\n\n"
            f"_Sourcing flags:_\n{facts}\n\n"
            f"_Voice drift:_\n{voice}\n"
        )

class _InternalPersonaCEO(BasicAgent):
    def __init__(self):
        self.name = "CEO"
        self.metadata = {
            "name": self.name,
            "description": "The CEO persona. Delegates to risk + decision specialists "
                           "and composes a strategic-message-discipline review.",
            "parameters": {
                "type": "object",
                "properties": {"input": {"type": "string", "description": "Content under review"}},
                "required": ["input"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, input="", **kwargs):
        risks    = _InternalCEORisk().perform(input=input)
        decision = _InternalCEODecision().perform(input=input)
        return f"**Decision**\n{decision}\n\n**Partner-conversation risks**\n{risks}\n"

# ─── PUBLIC ENTRYPOINT ──────────────────────────────────────────────────

class BookFactory(BasicAgent):
    def __init__(self):
        self.name = "BookFactory"
        self.metadata = {
            "name": self.name,
            "description": "Five-persona content pipeline. Source → Writer → Editor → "
                           "CEO → Publisher → Reviewer. Returns the final chapter.",
            "parameters": {
                "type": "object",
                "properties": {
                    "source":        {"type": "string", "description": "Raw source material"},
                    "chapter_title": {"type": "string", "description": "Working title"},
                    "author":        {"type": "string", "description": "Author byline"},
                    "workspace":     {"type": "string", "description": "Dir for intermediate artifacts"},
                },
                "required": ["source"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, source="", chapter_title="Untitled chapter",
                author="@rapp", workspace=None, **kwargs):
        ws = workspace or os.environ.get("TWIN_WORKSPACE") or "/tmp/book-factory"
        os.makedirs(ws, exist_ok=True)

        def save(name, content):
            path = os.path.join(ws, name)
            with open(path, "w") as f:
                f.write(content if isinstance(content, str) else str(content))
            return path

        save("00-source.md", source)

        # 1. Writer
        draft = _InternalPersonaWriter().perform(input=source, chapter_title=chapter_title)
        save("01-draft.md", draft)

        # 2. Editor (composite — calls cutweak + factcheck + voicecheck)
        edited = _InternalPersonaEditor().perform(input=draft)
        save("02-edited.md", edited)

        # 3. CEO (composite — calls risk + decision)
        ceo_note = _InternalPersonaCEO().perform(input=edited)
        save("03-ceo-note.md", ceo_note)

        # 4. Publisher
        final = _InternalPersonaPublisher().perform(input=edited, ceo_note=ceo_note,
                                                  title=chapter_title, author=author)
        save("04-final-chapter.md", final)

        # 5. Reviewer (read it cold)
        review = _InternalPersonaReviewer().perform(input=final)
        save("05-review.md", review)

        # Summary header + the final chapter (the artifact the caller wants)
        return (
            f"Book factory complete. Workspace: {ws}\n"
            f"---\n"
            f"FINAL CHAPTER:\n\n{final}\n"
            f"---\n"
            f"REVIEWER:\n\n{review}\n"
        )


# Alias so the brainstem's "name ends in Agent" discovery picks it up.
# (BookFactory is the canonical name; BookFactoryAgent is the discovery hook.)
class BookFactoryAgent(BookFactory):
    pass



# ─── Inlined LLM dispatch (one copy for the whole singleton) ──────────

def _llm_call(soul: str, user_prompt: str) -> str:
    messages = [{"role": "system", "content": soul},
                {"role": "user", "content": user_prompt}]
    try:
        from utils.llm import call_llm
        return call_llm(messages)
    except Exception as e:
        return f"(LLM dispatch error: {e})"


def _post(*args, **kwargs):
    # Retained as a no-op for build.py, which extracts _llm_call AND
    # _post from this file as the canonical singleton helpers. The
    # singleton no longer needs _post (utils.llm owns all HTTP), but
    # keeping a stub avoids touching the build script in this change.
    return ""
