"""
D365 Recipe Planner — Interviews you across seven discovery points and returns a copy-paste-ready Copilot Cowork prompt for a Dynamics 365 automation plus a predicted cost tier with the factors behind it; planning only, it never runs the reci

AGGREGATED ENTRY. The content authority for this capability is the upstream
library; this file is the structured RAR container for it. It carries a
manifest, a version locked to upstream, a content hash, a provenance record and
a public feedback thread — none of which the upstream entry has on its own.

This entry carries the upstream recipe itself, under its licence and with
attribution: the prompt verbatim, the prerequisites, the step-by-step and
the expected output. Toasting made it deterministic — the same call returns
the same recipe every time — and callable from any Brainstem. The upstream
library remains the authority for the recipe and links home for the source.

  Source library : Cowork Cookbook (Sean Galliher and Cowork Cookbook contributors)
  Upstream entry : https://coworkcookbook.com/recipes/d365-recipe-planner
  Upstream author: Sean Galliher and Cowork Cookbook contributors
  Upstream version: 1.0.0
  Licence        : CC-BY-4.0

Regenerated automatically by scripts/generate_aggregated_agents.py whenever the
upstream record changes, so this file and its source cannot silently diverge.
"""

__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": '@cowork-cookbook/d365_recipe_planner',
    "version": '3.0.3',
    "display_name": 'D365 Recipe Planner',
    "description": 'Interviews you across seven discovery points and returns a copy-paste-ready Copilot Cowork prompt for a Dynamics 365 automation plus a predicted cost tier with the factors behind it; planning only, it never runs the reci',
    "author": 'Sean Galliher and Cowork Cookbook contributors',
    "tags": ['industry_solution', 'business_process', 'prompt_skill', 'other', 'administer_to_operate', 'beginner', 'read_only'],
    "category": 'general',
    "quality_tier": 'verified',
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    # Provenance. `content_digest` fingerprints the upstream record; when it
    # moves, this file is regenerated. `--check` fails the build on drift.
    "source": {
        "aggregated": True,
        "source_id": 'cowork-cookbook',
        "source_name": 'Cowork Cookbook',
        "source_url": 'https://coworkcookbook.com/',
        "upstream_slug": 'd365-recipe-planner',
        "upstream_url": 'https://coworkcookbook.com/recipes/d365-recipe-planner',
        "upstream_version": '1.0.0',
        "license": 'CC-BY-4.0',
        "license_verified": True,
        "details": {'license_note': "Recipe content is CC BY 4.0 (share and adapt with attribution) and code is MIT. RAR carries each recipe's prompt, prerequisites, steps and expected output verbatim with attribution, so the toasted agent runs the real recipe; bundles and screenshots stay upstream.", 'license_url': 'https://github.com/seangalliher/Coworkcookbook/blob/main/LICENSE', 'repository_url': 'https://github.com/seangalliher/Coworkcookbook', 'taxonomy_url': 'https://coworkcookbook.com/data/taxonomy.json'},
        "content_digest": '32c43131c60f330e',
    },
    "industry_context": {'deprecated': False, 'difficulty': 'beginner', 'last_verified_on': '2026-07-28', 'mutates_data': False, 'plugin': 'none', 'process_roots': ['administer-to-operate'], 'process_tags': ['administer-to-operate/administer-system-features/configure-and-manage-copilot-capabilities'], 'recipe_category': 'other', 'recipe_type': 'prompt+skill', 'upstream_path': 'administer-to-operate/d365-recipe-planner', 'uses_skills': {'custom': ['d365-recipe-planner'], 'ootb': [], 'plugin': []}, 'verification_status': 'verified'},
    # The platforms the upstream entry targets. First-class and queryable, not
    # buried in prose: this is what lets the registry answer "what can I launch
    # into Copilot Studio / Cowork / Scout", which is the whole reason an
    # agent.py container beats a bare skill entry for cross-platform reach.
    "platforms": ['Microsoft 365 Copilot Cowork'],
}


try:
    from agents.basic_agent import BasicAgent
except ModuleNotFoundError:
    class BasicAgent:
        def __init__(self, name, metadata):
            self.name = name
            self.metadata = metadata


# The toasted capability, generated by @kody-w/skill_toaster_agent. A licensed
# recipe entry carries the upstream recipe verbatim (with attribution) in
# _SPEC["recipe"]; a metadata-only entry carries RAR's own method for that shape
# of work. See the module docstring for which this is.
_SPEC = {'archetype': 'recipe', 'checks': ['Prerequisite: Copilot Cowork access', 'Prerequisite: Install the d365-recipe-planner skill - either publish it as a Cowork plugin and turn it on under + > Customize, or drop the skill folder at Documents/Cowork/skills/d365-recipe-planner/ in your OneDrive', 'Prerequisite: No Dynamics 365 plugin is required: the planner writes prompts, it does not query D365', 'Prerequisite: Optional: enable a Dynamics 365 Sales or ERP plugin if you want the planner to confirm entity names against your tenant before finalizing a prompt', 'Output matches: A conversational recipe summary, a fenced copy-paste prompt, and a cost tier naming the two to four factors that drove the score. On request, a Cookbook-format `.md` recipe file saved to your Cowork output folder.\n\nThe capture below is a real run. From the brief "keep an eye on overdue customer invoices", the skill produced an **AR Overdue Invoice Monitor** recipe: it identified the surface as D365 Finance via the `dynamics-365-erp` plugin scoped to legal entity USMF, set the mode to read-only, drafted a four-part prompt with lettered deliverable requirements for an interactive HTML aging dashboard, and scored the plan **Medium** — naming the HTML-with-charts deliverable as the largest cost driver.\n\nNote how the drafted prompt tells Cowork to *confirm the exact open-balance entity in the tenant before querying* and to *say what it found instead of guessing* if that entity cannot be confirmed. That is the skill\'s no-fabrication guardrail reaching into the prompts it writes.'], 'confidence': 1.0, 'deliverable': 'A conversational recipe summary, a fenced copy-paste prompt, and a cost tier naming the two to four factors that drove the score. On request, a Cookbook-format `.md` recipe file saved to your Cowork output folder.\n\nThe capture below is a real run. From the brief "keep an eye on overdue customer invoices", the skill produced an **AR Overdue Invoice Monitor** recipe: it identified the surface as D365 Finance via the `dynamics-365-erp` plugin scoped to legal entity USMF, set the mode to read-only, drafted a four-part prompt with lettered deliverable requirements for an interactive HTML aging dashboard, and scored the plan **Medium** — naming the HTML-with-charts deliverable as the largest cost driver.\n\nNote how the drafted prompt tells Cowork to *confirm the exact open-balance entity in the tenant before querying* and to *say what it found instead of guessing* if that entity cannot be confirmed. That is the skill\'s no-fabrication guardrail reaching into the prompts it writes.', 'operations': ['run', 'prompt', 'plan', 'checklist', 'describe'], 'params': {'business_outcome': 'The business outcome you want and the process to automate.', 'context': 'Optional. Details the recipe should use — the record, scope, dates or filters it asks for.', 'd365_app': 'Which D365 surface: Sales, Finance, or ERP/Supply Chain.', 'data_scope_and_frequency': 'Data scope (e.g. legal entity, records, date range) and how often it should run.', 'deliverable_format': 'Desired output format, e.g. summary, HTML dashboard, or Cookbook .md recipe file.', 'mode': 'Read-only versus write-back.'}, 'recipe': {'authors': ['Sean Galliher'], 'business_value': 'Lowers the barrier to authoring Cowork automations. A short interview replaces trial-and-error prompt writing, the generated prompt names the correct plugin and scope anchor for the chosen app, and the cost tier tells you what a run commits you to before you make it.', 'expected_output': 'A conversational recipe summary, a fenced copy-paste prompt, and a cost tier naming the two to four factors that drove the score. On request, a Cookbook-format `.md` recipe file saved to your Cowork output folder.\n\nThe capture below is a real run. From the brief "keep an eye on overdue customer invoices", the skill produced an **AR Overdue Invoice Monitor** recipe: it identified the surface as D365 Finance via the `dynamics-365-erp` plugin scoped to legal entity USMF, set the mode to read-only, drafted a four-part prompt with lettered deliverable requirements for an interactive HTML aging dashboard, and scored the plan **Medium** — naming the HTML-with-charts deliverable as the largest cost driver.\n\nNote how the drafted prompt tells Cowork to *confirm the exact open-balance entity in the tenant before querying* and to *say what it found instead of guessing* if that entity cannot be confirmed. That is the skill\'s no-fabrication guardrail reaching into the prompts it writes.', 'platform': 'Microsoft 365 Copilot Cowork', 'prerequisites': ['Copilot Cowork access', 'Install the d365-recipe-planner skill - either publish it as a Cowork plugin and turn it on under + > Customize, or drop the skill folder at Documents/Cowork/skills/d365-recipe-planner/ in your OneDrive', 'No Dynamics 365 plugin is required: the planner writes prompts, it does not query D365', 'Optional: enable a Dynamics 365 Sales or ERP plugin if you want the planner to confirm entity names against your tenant before finalizing a prompt'], 'prompt': 'Activate the **D365 Recipe Planner** skill for this conversation. I want to plan a new Dynamics 365 Cowork recipe.\n\nInterview me on the seven discovery points — business outcome, the process to automate, which D365 app (Sales, Finance, or ERP/Supply Chain), deliverable format, read-only versus write-back, data scope, and frequency — then draft a copy-paste-ready Cowork prompt and predict its cost tier with the factors that drove the score.\n\nPlan only. Do not run the recipe or pull any records while we design it.', 'steps': ['Install the skill by whichever route you prefer — publish it as a Cowork plugin, or unzip the package below into `Documents/Cowork/skills/` so the folder lands at `Documents/Cowork/skills/d365-recipe-planner/`.', 'Start a new Cowork task. If you installed it as a plugin, turn it on under **+ > Customize**. If you installed it as a skill folder, Cowork discovers it automatically at the start of each conversation — there is no registration step.', 'Paste the prompt from `prompt.md`, or simply describe what you want to automate; the skill\'s description makes it self-invoking on phrases like "plan a recipe" or "help me automate a D365 task".', 'Answer the discovery questions. If you already have a rich brief, give it up front and the skill will skip ahead.', 'Copy the generated prompt into a **fresh** task to actually run it. The planner deliberately will not execute it for you.'], 'tenant_caveat': '', 'verified_against': 'm365.cloud.microsoft 2026-07-28', 'what_it_does': 'Runs a short discovery interview across seven points — business outcome, process, D365 app, deliverable format, read-only versus write-back, data scope, and frequency — then:\n\n1. Maps the chosen app to the correct Cowork plugin and scope anchor. Finance and ERP/Supply Chain are the same product (F&SCM) and share the `dynamics-365-erp` surface with a **legal entity** scope; Sales is a separate product on Dataverse scoped by **environment**.\n2. Drafts a single copy-paste prompt with an explicit scope line, the data to pull, lettered deliverable requirements, an output location, and guardrails appropriate to read-only versus write-back.\n3. Scores the plan against a seven-factor rubric and reports a low / medium / high cost tier **with the factors that drove it**, plus one suggestion for moving it down a tier.\n4. Optionally saves the result as a Cookbook-format recipe markdown file.\n\nIt plans and drafts only. Its own guardrails forbid pulling, modifying, or creating records — the single live call it permits is a read-only schema lookup to confirm an entity exists.'}, 'refined_by': 'claude-opus-5', 'refinement': {'description': 'Interviews you across seven discovery points and returns a copy-paste-ready Copilot Cowork prompt for a Dynamics 365 automation plus a predicted cost tier with the factors behind it; planning only, it never runs the reci', 'example_request': 'Help me plan a D365 recipe to monitor overdue customer invoices in Finance and tell me the cost tier.', 'inputs': [{'description': 'The business outcome you want and the process to automate.', 'name': 'business_outcome'}, {'description': 'Which D365 surface: Sales, Finance, or ERP/Supply Chain.', 'name': 'd365_app'}, {'description': 'Desired output format, e.g. summary, HTML dashboard, or Cookbook .md recipe file.', 'name': 'deliverable_format'}, {'description': 'Read-only versus write-back.', 'name': 'mode'}, {'description': 'Data scope (e.g. legal entity, records, date range) and how often it should run.', 'name': 'data_scope_and_frequency'}], 'model': 'claude-opus-5', 'when_to_use': 'Call when you want to plan or draft a Dynamics 365 Cowork recipe prompt and estimate its cost tier before running it in a fresh task.'}, 'signals': ['recipe:prompt', 'refined'], 'steps': ['Install the skill by whichever route you prefer — publish it as a Cowork plugin, or unzip the package below into `Documents/Cowork/skills/` so the folder lands at `Documents/Cowork/skills/d365-recipe-planner/`.', 'Start a new Cowork task. If you installed it as a plugin, turn it on under **+ > Customize**. If you installed it as a skill folder, Cowork discovers it automatically at the start of each conversation — there is no registration step.', 'Paste the prompt from `prompt.md`, or simply describe what you want to automate; the skill\'s description makes it self-invoking on phrases like "plan a recipe" or "help me automate a D365 task".', 'Answer the discovery questions. If you already have a rich brief, give it up front and the skill will skip ahead.', 'Copy the generated prompt into a **fresh** task to actually run it. The planner deliberately will not execute it for you.'], 'subject_label': 'context for the recipe', 'verb': 'Run'}


class D365RecipePlanner(BasicAgent):
    """Run agent, toasted from an aggregated upstream entry."""

    def __init__(self):
        self.name = 'D365RecipePlanner'
        self.metadata = {
            "name": self.name,
            "display_name": __manifest__["display_name"],
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {'business_outcome': {'description': 'The business outcome you want and the process to automate.', 'type': 'string'}, 'context': {'description': 'Optional. Details the recipe should use — the record, scope, dates or filters it asks for.', 'type': 'string'}, 'd365_app': {'description': 'Which D365 surface: Sales, Finance, or ERP/Supply Chain.', 'type': 'string'}, 'data_scope_and_frequency': {'description': 'Data scope (e.g. legal entity, records, date range) and how often it should run.', 'type': 'string'}, 'deliverable_format': {'description': 'Desired output format, e.g. summary, HTML dashboard, or Cookbook .md recipe file.', 'type': 'string'}, 'mode': {'description': 'Read-only versus write-back.', 'type': 'string'}, 'operation': {'description': 'What to do: run, prompt, plan, checklist, describe.', 'enum': ['run', 'prompt', 'plan', 'checklist', 'describe'], 'type': 'string'}},
                "required": ["operation"],
            },
        }
        super().__init__(self.name, self.metadata)

    # ── helpers ─────────────────────────────────────────────────────────

    def _subject(self, kwargs):
        for key in ("subject", "input", "target", "topic"):
            value = str(kwargs.get(key) or "").strip()
            if value:
                return value
        return ""

    def _header(self, subject):
        label = subject or f"<no {_SPEC['subject_label']} supplied>"
        return f"{_SPEC['verb']}: {label}"

    def _context(self, kwargs):
        extras = []
        for key in _SPEC["params"]:
            if key == "subject":
                continue
            value = str(kwargs.get(key) or "").strip()
            if value:
                extras.append(f"{key}: {value}")
        return extras

    def _plan(self, subject, kwargs):
        lines = [self._header(subject)]
        extras = self._context(kwargs)
        if extras:
            lines += ["", "Context:"] + [f"  {e}" for e in extras]
        lines += ["", "Procedure:"]
        lines += [f"  {i}. {step}" for i, step in enumerate(_SPEC["steps"], 1)]
        if not subject:
            lines += [
                "",
                f"Pass subject=\u0022...\u0022 to bind this procedure to a "
                f"specific {_SPEC['subject_label']}.",
            ]
        return lines

    def _checklist(self):
        return ["Acceptance checks:"] + [f"  [ ] {c}" for c in _SPEC["checks"]]

    def _provenance(self):
        src = __manifest__["source"]
        lines = [
            f"{__manifest__['display_name']} (v{__manifest__['version']})",
            "",
            __manifest__["description"],
            "",
            f"Capability shape: {_SPEC['archetype']} "
            f"(confidence {_SPEC['confidence']})",
        ]
        platforms = __manifest__.get("platforms") or []
        if platforms:
            lines.append("Runs on:          " + ", ".join(platforms))
        lines += [
            "",
            f"Indexed from:     {src['source_name']}",
            f"Upstream entry:   {src['upstream_url']}",
            f"Upstream author:  {__manifest__['author']}",
            "",
            "RAR indexes this capability and implements its method; the "
            "upstream library remains the authority for its own instructions. "
            "Open the link above to get those from the source.",
        ]
        return lines

    # ── recipe entries: the upstream recipe, verbatim, deterministic ─────

    def _recipe_context(self, kwargs):
        extras = []
        subject = self._subject(kwargs)
        if subject:
            extras.append(f"subject: {subject}")
        for key in _SPEC["params"]:
            value = str(kwargs.get(key) or "").strip()
            if value:
                extras.append(f"{key}: {value}")
        return extras

    def _recipe_prompt(self, kwargs):
        r = _SPEC["recipe"]
        lines = [r["prompt"]]
        extras = self._recipe_context(kwargs)
        if extras:
            lines += ["", "Context supplied by the caller:"] + [f"- {e}" for e in extras]
        return lines

    def _recipe_attribution(self):
        src = __manifest__["source"]
        r = _SPEC["recipe"]
        who = ", ".join(r.get("authors") or []) or __manifest__["author"]
        return [
            f"Recipe: {__manifest__['display_name']} — by {who}, {src['source_name']} "
            f"({src['license']}). Source: {src['upstream_url']}",
        ]

    def _perform_recipe(self, op, kwargs):
        r = _SPEC["recipe"]
        ref = _SPEC.get("refinement") or {}
        if op == "prompt":
            return "\n".join(self._recipe_prompt(kwargs) + [""] + self._recipe_attribution())
        if op == "plan":
            lines = [f"Steps for {__manifest__['display_name']} on {r['platform']}:"]
            lines += [f"  {i}. {s}" for i, s in enumerate(r["steps"], 1)]
            return "\n".join(lines + [""] + self._recipe_attribution())
        if op == "checklist":
            lines = ["Before you run it:"] + [f"  [ ] {p}" for p in r["prerequisites"]]
            if r.get("expected_output"):
                lines += ["", "Done when:", f"  [ ] {r['expected_output']}"]
            return "\n".join(lines + [""] + self._recipe_attribution())
        if op == "describe":
            lines = self._provenance()
            if ref.get("when_to_use"):
                lines += ["", f"When to use: {ref['when_to_use']}"]
            if ref.get("example_request"):
                lines += [f"Ask for it like: {ref['example_request']}"]
            if ref.get("inputs"):
                lines += ["", "It will ask you for:"] + [f"  - {i['name']}: {i['description']}" for i in ref["inputs"]]
            if r.get("business_value"):
                lines += ["", f"Why it matters: {r['business_value']}"]
            return "\n".join(lines)
        if op == "run":
            lines = [f"{__manifest__['display_name']} — run on {r['platform']}", ""]
            if r.get("what_it_does"):
                lines += [r["what_it_does"], ""]
            lines += [f"Prompt (paste into {r['platform']}):", ""] + self._recipe_prompt(kwargs) + [""]
            lines += ["Procedure:"] + [f"  {i}. {s}" for i, s in enumerate(r["steps"], 1)] + [""]
            lines += ["Acceptance checks:"] + [f"  [ ] {c}" for c in _SPEC["checks"]] + [""]
            lines += [f"Deliverable: {_SPEC['deliverable']}", ""]
            if r.get("tenant_caveat"):
                lines += [f"Verified upstream: {r['tenant_caveat']}", ""]
            return "\n".join(lines + self._recipe_attribution())
        return (
            f"Unknown operation {op!r}. Valid operations: "
            + ", ".join(_SPEC["operations"])
        )

    # ── entry point ─────────────────────────────────────────────────────

    def perform(self, **kwargs):
        """Run the toasted capability. Always returns a string."""
        op = str(kwargs.get("operation") or "run").strip().lower()
        subject = self._subject(kwargs)

        if _SPEC.get("recipe"):
            return self._perform_recipe(op, kwargs)

        if op == "describe":
            return "\n".join(self._provenance())

        if op == "checklist":
            return "\n".join([self._header(subject), ""] + self._checklist())

        if op == "plan":
            return "\n".join(self._plan(subject, kwargs))

        if op == "run":
            lines = self._plan(subject, kwargs)
            lines += [""] + self._checklist()
            lines += ["", f"Deliverable: {_SPEC['deliverable']}"]
            lines += ["", f"Source: {__manifest__['source']['upstream_url']}"]
            return "\n".join(lines)

        return (
            f"Unknown operation {op!r}. Valid operations: "
            + ", ".join(_SPEC["operations"])
        )


if __name__ == "__main__":
    print(D365RecipePlanner().perform(operation="run"))
