/**
 * Marketplace packaging for an approved Show-and-Tell plan.
 *
 * The directory shape — `.claude-plugin/marketplace.json`, then
 * `plugins/<plugin>/.claude-plugin/plugin.json`, then
 * `plugins/<plugin>/skills/<skill>/SKILL.md` — is the layout skill
 * marketplaces already agree on, so an OpenRappter recording drops into one
 * without a conversion step. The implementation here is OpenRappter's own and
 * carries no other project's code, branding, ownership, or endorsement.
 *
 * Export writes only into a private OpenRappter directory, refuses to escape
 * it, and refuses to write anything a privacy scan flags.
 *
 * Mirrored in `python/openrappter/show_and_tell_marketplace.py`.
 */

import { createHash } from 'node:crypto';
import { existsSync, lstatSync, mkdirSync, readFileSync } from 'node:fs';
import path from 'node:path';

import { openrappterPath } from '../infra/openrappter-home.js';
import {
  assertPrivateDirectory,
  hardenPrivatePath,
} from '../flight-recorder/permissions.js';
import {
  artifactContainsSensitiveText,
  compareStrings,
  hasSecretFindings,
  scanSensitivePayload,
} from './privacy.js';
import {
  SHOW_AND_TELL_MARKETPLACE_SCHEMA,
  type ShowAndTellSkillPlan,
} from './types.js';

export const MARKETPLACE_ATTRIBUTION =
  'Generated by OpenRappter Show-and-Tell. The directory layout follows an ' +
  'open skill marketplace convention. This package is not affiliated with, ' +
  'owned by, or endorsed by any third party, including Microsoft.';

const NAME_PATTERN = /^[a-z0-9][a-z0-9-]{0,62}$/;

/** Phrases that would claim someone else's ownership of a generated export. */
const FALSE_OWNERSHIP =
  /\b(?:(?:endorsed|owned|certified|maintained|published|approved)\s+by\s+(?:microsoft|power\s*cat)|official\s+(?:microsoft|power\s*cat)|microsoft\s+corporation)\b/i;

export interface MarketplaceExportInput {
  plan: ShowAndTellSkillPlan;
  /** Marketplace directory name. Defaults to the OpenRappter marketplace. */
  marketplaceName?: string;
  /** Plugin directory name. Defaults to the plan slug. */
  pluginName?: string;
  /** Skill directory name. Defaults to the plan slug. */
  skillName?: string;
  /** Export root. Defaults to `$OPENRAPPTER_MARKETPLACE_DIR`. */
  root?: string;
  version?: string;
}

export interface MarketplaceExport {
  schema: typeof SHOW_AND_TELL_MARKETPLACE_SCHEMA;
  root: string;
  marketplaceName: string;
  pluginName: string;
  skillName: string;
  files: string[];
  marketplacePath: string;
  pluginPath: string;
  skillPath: string;
  contentHash: string;
  attribution: string;
}

export interface MarketplaceCheck {
  name: string;
  ok: boolean;
  detail: string;
}

export function marketplaceRoot(): string {
  return path.resolve(
    process.env.OPENRAPPTER_MARKETPLACE_DIR ?? openrappterPath('marketplace'),
  );
}

export function slugifyMarketplaceName(value: string, fallback: string): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 62)
    .replace(/-+$/g, '');
  return NAME_PATTERN.test(slug) ? slug : fallback;
}

function privateDirectory(directory: string): void {
  mkdirSync(directory, { recursive: true, mode: 0o700 });
  const stat = lstatSync(directory);
  if (stat.isSymbolicLink() || !stat.isDirectory()) {
    throw new Error(`Marketplace path is not a private directory: ${directory}`);
  }
  hardenPrivatePath(directory, true);
  assertPrivateDirectory(directory);
}

/** Refuses any name that could walk out of the export root. */
function containedPath(root: string, ...segments: string[]): string {
  for (const segment of segments) {
    if (!NAME_PATTERN.test(segment)) {
      throw new Error(`Unsafe marketplace path segment: ${segment}`);
    }
  }
  const candidate = path.resolve(root, ...segments);
  const relative = path.relative(root, candidate);
  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new Error(`Marketplace path escapes the export root: ${candidate}`);
  }
  return candidate;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

/**
 * The one-line trigger contract a skill host reads before loading anything
 * else. Keeping USE WHEN / USE FOR / DO NOT USE WHEN in the description is
 * what stops a recorded workflow being loaded for a task it never saw.
 */
export function renderSkillDescription(plan: ShowAndTellSkillPlan): string {
  const useWhen = plan.useWhen.join(' ');
  const useFor = plan.useFor.join('; ');
  const doNot = plan.doNotUseWhen.join(' ');
  return (
    `USE WHEN: ${useWhen} ` +
    `USE FOR: ${useFor}. ` +
    `DO NOT USE WHEN: ${doNot}`
  ).replace(/\s+/g, ' ').trim();
}

export function renderMarketplaceSkill(
  plan: ShowAndTellSkillPlan,
  skillName: string,
): string {
  const tools = [...new Set(plan.steps.map((step) => step.tool).filter(Boolean))];
  const lines = [
    '---',
    `name: ${skillName}`,
    `description: ${yamlString(renderSkillDescription(plan))}`,
    'metadata:',
    `  source: ${yamlString('openrappter-show-and-tell')}`,
    `  session: ${yamlString(plan.sessionId)}`,
    `  planRevision: ${plan.revision}`,
    `  analysisRevision: ${plan.analysisRevision}`,
    `  attribution: ${yamlString(MARKETPLACE_ATTRIBUTION)}`,
  ];
  if (tools.length) {
    lines.push('allowed-tools:');
    for (const tool of tools) lines.push(`  - ${yamlString(tool)}`);
  }
  lines.push('---', '', `# ${plan.title}`, '', '## Goal', '', plan.intent, '');

  lines.push('## Use when', '');
  for (const entry of plan.useWhen) lines.push(`- ${entry}`);
  lines.push('', '## Use for', '');
  for (const entry of plan.useFor) lines.push(`- ${entry}`);
  lines.push('', '## Do not use when', '');
  for (const entry of plan.doNotUseWhen) lines.push(`- ${entry}`);

  lines.push('', '## Inputs', '');
  if (plan.values.length === 0) {
    lines.push('This workflow took no values from the demonstration.');
  } else {
    lines.push(
      'These came from one demonstration. Substitute them per run; do not treat them as constants.',
      '',
      '| Placeholder | Meaning | Recorded example |',
      '| --- | --- | --- |',
    );
    for (const value of plan.values) {
      lines.push(
        `| \`{{${value.id}}}\` | ${value.label} | ${
          value.exampleMasked ? 'withheld by privacy scan' : `\`${value.example}\``
        } |`,
      );
    }
  }

  lines.push('', '## Procedure', '');
  plan.steps.forEach((step, index) => {
    const suffix = [
      step.tool ? ` Prefer \`${step.tool}\`.` : '',
      step.url ? ` Destination: ${step.url}` : '',
      step.requiresConfirmation
        ? ` Ask for confirmation first (${step.riskCategories.join(', ')}).`
        : '',
    ].join('');
    lines.push(`${index + 1}. **${step.title}** — ${step.detail}${suffix}`);
  });

  lines.push(
    '',
    '## Execution rules',
    '',
    '- Prefer a native API, CLI, filesystem, or browser tool over replaying screen coordinates.',
    '- Re-locate controls by meaning, not by recorded pixels.',
    '- Stop and ask before destructive, financial, publishing, or message-sending steps.',
    '- Never request, persist, or echo credentials from the demonstration.',
    '',
    '## Evidence and limits',
    '',
    `- Reconstructed from ${plan.evidenceStats.meaningfulEventCount} recorded event(s) in ${plan.evidenceStats.segmentCount} segment(s).`,
    `- ${plan.evidenceStats.silentEvents} event(s) had no narration; ${plan.evidenceStats.unexplainedFrames} frame(s) had no label.`,
    `- ${plan.evidenceStats.detourSegments} segment(s) were treated as detours.`,
    '- Raw screenshots were never shared with a model.',
    '',
  );
  if (plan.openQuestions.length) {
    lines.push('### Open questions', '');
    for (const question of plan.openQuestions) lines.push(`- ${question}`);
    lines.push('');
  }
  lines.push('## Provenance', '', `- ${MARKETPLACE_ATTRIBUTION}`, '');
  return lines.join('\n');
}

export function renderMarketplaceManifest(
  plan: ShowAndTellSkillPlan,
  input: {
    marketplaceName: string;
    pluginName: string;
    skillName: string;
    version: string;
  },
): string {
  return `${JSON.stringify(
    {
      name: input.marketplaceName,
      owner: {
        name: 'OpenRappter Show-and-Tell',
        url: 'https://github.com/kody-w/openrappter',
      },
      metadata: {
        description:
          'Skills recorded locally with OpenRappter Show-and-Tell and approved by their author.',
        version: input.version,
        attribution: MARKETPLACE_ATTRIBUTION,
      },
      plugins: [
        {
          name: input.pluginName,
          source: `./plugins/${input.pluginName}`,
          description: renderSkillDescription(plan),
          version: input.version,
          author: { name: 'OpenRappter Show-and-Tell' },
          keywords: ['openrappter', 'show-and-tell', 'recorded-workflow'],
          skills: [`./skills/${input.skillName}`],
        },
      ],
    },
    null,
    2,
  )}\n`;
}

export function renderPluginManifest(
  plan: ShowAndTellSkillPlan,
  input: { pluginName: string; skillName: string; version: string },
): string {
  return `${JSON.stringify(
    {
      name: input.pluginName,
      description: renderSkillDescription(plan),
      version: input.version,
      author: { name: 'OpenRappter Show-and-Tell' },
      keywords: ['openrappter', 'show-and-tell', 'recorded-workflow'],
      skills: [`./skills/${input.skillName}`],
      metadata: {
        source: 'openrappter-show-and-tell',
        sessionId: plan.sessionId,
        planRevision: plan.revision,
        analysisRevision: plan.analysisRevision,
        requiresConfirmation: plan.steps.some((step) => step.requiresConfirmation),
        attribution: MARKETPLACE_ATTRIBUTION,
      },
    },
    null,
    2,
  )}\n`;
}

export interface MarketplaceFile {
  path: string;
  content: string;
}

/**
 * Renders the export without touching disk, so the same shape can be
 * validated in a test, previewed in a review, or written once.
 */
export function renderMarketplaceExport(input: MarketplaceExportInput): {
  files: MarketplaceFile[];
  root: string;
  marketplaceName: string;
  pluginName: string;
  skillName: string;
} {
  const { plan } = input;
  if (!plan.approved) {
    throw new Error('Approve the Show-and-Tell plan before exporting it.');
  }
  const root = path.resolve(input.root ?? marketplaceRoot());
  const fallback = slugifyMarketplaceName(plan.title || plan.intent, 'recorded-workflow');
  const marketplaceName = slugifyMarketplaceName(
    input.marketplaceName ?? 'openrappter-show-and-tell',
    'openrappter-show-and-tell',
  );
  const pluginName = slugifyMarketplaceName(input.pluginName ?? fallback, fallback);
  const skillName = slugifyMarketplaceName(input.skillName ?? fallback, fallback);
  const version = /^\d+\.\d+\.\d+$/.test(input.version ?? '')
    ? (input.version as string)
    : `1.0.${Math.max(0, plan.revision - 1)}`;

  const marketplaceDirectory = containedPath(root, marketplaceName);
  const files: MarketplaceFile[] = [
    {
      path: path.join(marketplaceDirectory, '.claude-plugin', 'marketplace.json'),
      content: renderMarketplaceManifest(plan, {
        marketplaceName,
        pluginName,
        skillName,
        version,
      }),
    },
    {
      path: path.join(
        containedPath(marketplaceDirectory, 'plugins', pluginName),
        '.claude-plugin',
        'plugin.json',
      ),
      content: renderPluginManifest(plan, { pluginName, skillName, version }),
    },
    {
      path: path.join(
        containedPath(marketplaceDirectory, 'plugins', pluginName, 'skills', skillName),
        'SKILL.md',
      ),
      content: renderMarketplaceSkill(plan, skillName),
    },
  ];
  return { files, root: marketplaceDirectory, marketplaceName, pluginName, skillName };
}

export function marketplaceContentHash(files: readonly MarketplaceFile[]): string {
  const digest = createHash('sha256');
  for (const file of [...files].sort((left, right) =>
    compareStrings(left.path, right.path),
  )) {
    digest.update(path.basename(file.path)).update('\0').update(file.content).update('\0');
  }
  return digest.digest('hex');
}

export type MarketplaceWriter = (file: string, content: string) => void;

/**
 * Writes the export. The caller supplies the writer so the atomic,
 * mode-0600 write used everywhere else in Show-and-Tell is reused rather than
 * reimplemented here.
 */
export function writeMarketplaceExport(
  input: MarketplaceExportInput,
  write: MarketplaceWriter,
): MarketplaceExport {
  const rendered = renderMarketplaceExport(input);
  for (const file of rendered.files) {
    const findings = scanSensitivePayload(file.content, path.basename(file.path));
    if (hasSecretFindings(findings) || artifactContainsSensitiveText(file.content)) {
      throw new Error(
        `Privacy scan rejected the generated ${path.basename(file.path)}.`,
      );
    }
    if (FALSE_OWNERSHIP.test(file.content)) {
      throw new Error(
        `Refusing to publish ${path.basename(file.path)}: it claims third-party ownership or endorsement.`,
      );
    }
  }
  privateDirectory(rendered.root);
  for (const file of rendered.files) {
    privateDirectory(path.dirname(file.path));
    write(file.path, file.content);
  }
  return {
    schema: SHOW_AND_TELL_MARKETPLACE_SCHEMA,
    root: rendered.root,
    marketplaceName: rendered.marketplaceName,
    pluginName: rendered.pluginName,
    skillName: rendered.skillName,
    files: rendered.files.map((file) => file.path),
    marketplacePath: rendered.files[0].path,
    pluginPath: rendered.files[1].path,
    skillPath: rendered.files[2].path,
    contentHash: marketplaceContentHash(rendered.files),
    attribution: MARKETPLACE_ATTRIBUTION,
  };
}

function readIfPresent(file: string): string | null {
  if (!existsSync(file)) return null;
  const stat = lstatSync(file);
  if (stat.isSymbolicLink() || !stat.isFile()) return null;
  return readFileSync(file, 'utf8');
}

/**
 * Validates an exported marketplace on disk: layout, manifest shape, name
 * agreement, trigger metadata, privacy, and ownership honesty.
 */
export function validateMarketplaceExport(
  marketplaceDirectory: string,
): { ok: boolean; checks: MarketplaceCheck[] } {
  const checks: MarketplaceCheck[] = [];
  const add = (name: string, ok: boolean, detail: string) => {
    checks.push({ name, ok, detail });
  };
  const root = path.resolve(marketplaceDirectory);
  const marketplaceFile = path.join(root, '.claude-plugin', 'marketplace.json');
  const marketplaceRaw = readIfPresent(marketplaceFile);
  add(
    'marketplace-manifest-exists',
    marketplaceRaw !== null,
    marketplaceRaw !== null ? marketplaceFile : `Missing ${marketplaceFile}`,
  );
  if (marketplaceRaw === null) return { ok: false, checks };

  let marketplace: Record<string, unknown>;
  try {
    marketplace = JSON.parse(marketplaceRaw) as Record<string, unknown>;
  } catch (error) {
    add(
      'marketplace-manifest-json',
      false,
      `marketplace.json is not valid JSON: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
    return { ok: false, checks };
  }
  add('marketplace-manifest-json', true, 'marketplace.json parses.');

  const marketplaceName = marketplace.name;
  add(
    'marketplace-name',
    typeof marketplaceName === 'string' && NAME_PATTERN.test(marketplaceName),
    typeof marketplaceName === 'string'
      ? `Marketplace name is "${marketplaceName}".`
      : 'Marketplace name is missing.',
  );

  const plugins = Array.isArray(marketplace.plugins) ? marketplace.plugins : [];
  add(
    'marketplace-plugins',
    plugins.length > 0,
    `${plugins.length} plugin entry/entries declared.`,
  );

  const seen = new Set<string>();
  for (const entry of plugins) {
    const plugin = (entry ?? {}) as Record<string, unknown>;
    const name = typeof plugin.name === 'string' ? plugin.name : '';
    const source = typeof plugin.source === 'string' ? plugin.source : '';
    add(
      `plugin-name:${name || '(unnamed)'}`,
      NAME_PATTERN.test(name) && !seen.has(name),
      seen.has(name)
        ? `Duplicate plugin name ${name}.`
        : `Plugin name is "${name}".`,
    );
    seen.add(name);

    const resolved = path.resolve(root, source);
    const contained =
      source.startsWith('./') &&
      !path.relative(root, resolved).startsWith('..') &&
      !path.isAbsolute(path.relative(root, resolved));
    add(
      `plugin-source:${name}`,
      contained,
      contained
        ? `Source ${source} stays inside the marketplace.`
        : `Source ${source} escapes the marketplace root.`,
    );
    if (!contained) continue;

    const pluginFile = path.join(resolved, '.claude-plugin', 'plugin.json');
    const pluginRaw = readIfPresent(pluginFile);
    add(
      `plugin-manifest:${name}`,
      pluginRaw !== null,
      pluginRaw !== null ? pluginFile : `Missing ${pluginFile}`,
    );
    if (pluginRaw === null) continue;

    let plugin_json: Record<string, unknown>;
    try {
      plugin_json = JSON.parse(pluginRaw) as Record<string, unknown>;
    } catch (error) {
      add(
        `plugin-manifest-json:${name}`,
        false,
        `plugin.json is not valid JSON: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
      continue;
    }
    add(
      `plugin-manifest-json:${name}`,
      plugin_json.name === name,
      plugin_json.name === name
        ? 'plugin.json name matches the marketplace entry.'
        : `plugin.json name ${String(plugin_json.name)} does not match ${name}.`,
    );

    const declared = Array.isArray(plugin_json.skills) ? plugin_json.skills : [];
    add(
      `plugin-skills:${name}`,
      declared.length > 0,
      `${declared.length} skill(s) declared.`,
    );
    for (const skillEntry of declared) {
      const relative = typeof skillEntry === 'string' ? skillEntry : '';
      const skillDirectory = path.resolve(resolved, relative);
      const insideSkills =
        relative.startsWith('./skills/') &&
        !path.relative(resolved, skillDirectory).startsWith('..');
      add(
        `skill-path:${relative || '(unnamed)'}`,
        insideSkills,
        insideSkills
          ? `${relative} resolves inside the plugin.`
          : `${relative} does not resolve inside the plugin's skills directory.`,
      );
      if (!insideSkills) continue;
      const skillFile = path.join(skillDirectory, 'SKILL.md');
      const skill = readIfPresent(skillFile);
      add(
        `skill-file:${path.basename(skillDirectory)}`,
        skill !== null,
        skill !== null ? skillFile : `Missing ${skillFile}`,
      );
      if (skill === null) continue;
      const frontmatter = /^---\n([\s\S]*?)\n---/.exec(skill);
      const declaredName = frontmatter
        ? /^name:\s*(.+)$/m.exec(frontmatter[1])?.[1]?.trim()
        : undefined;
      add(
        `skill-frontmatter:${path.basename(skillDirectory)}`,
        declaredName === path.basename(skillDirectory),
        declaredName
          ? `Frontmatter name is "${declaredName}".`
          : 'SKILL.md has no frontmatter name.',
      );
      const description = frontmatter
        ? /^description:\s*(.+)$/m.exec(frontmatter[1])?.[1] ?? ''
        : '';
      const hasTriggers =
        // "DO NOT USE WHEN:" ends in "USE WHEN:", so a plain substring test
        // reports a description that lost its positive trigger as complete.
        /(?<!DO NOT )USE WHEN:/.test(description) &&
        /USE FOR:/.test(description) &&
        /DO NOT USE WHEN:/.test(description);
      add(
        `skill-triggers:${path.basename(skillDirectory)}`,
        hasTriggers,
        hasTriggers
          ? 'Description declares USE WHEN, USE FOR, and DO NOT USE WHEN.'
          : 'Description is missing USE WHEN, USE FOR, or DO NOT USE WHEN.',
      );
      const skillFindings = scanSensitivePayload(skill, 'SKILL.md');
      add(
        `skill-privacy:${path.basename(skillDirectory)}`,
        !hasSecretFindings(skillFindings) && !artifactContainsSensitiveText(skill),
        hasSecretFindings(skillFindings)
          ? `Secret-shaped text found: ${skillFindings
              .map((finding) => finding.kind)
              .join(', ')}`
          : 'No secret-shaped text.',
      );
      add(
        `skill-attribution:${path.basename(skillDirectory)}`,
        skill.includes(MARKETPLACE_ATTRIBUTION) && !FALSE_OWNERSHIP.test(skill),
        skill.includes(MARKETPLACE_ATTRIBUTION)
          ? 'Attribution present and claims no third-party endorsement.'
          : 'Attribution is missing or claims third-party ownership.',
      );
    }
  }

  const ownershipHonest = !FALSE_OWNERSHIP.test(marketplaceRaw);
  add(
    'marketplace-ownership',
    ownershipHonest,
    ownershipHonest
      ? 'marketplace.json claims no third-party ownership or endorsement.'
      : 'marketplace.json claims third-party ownership or endorsement.',
  );

  return { ok: checks.every((check) => check.ok), checks };
}
