/**
 * ClawHub Integration for openrappter (TypeScript)
 * Skills are public GitHub repos with skill.json + skill.md at their root.
 * Install by repo: "owner/repo" (e.g., "kody-w/rappterverse")
 */

import { execFile } from 'child_process';
import { promisify } from 'util';
import { readFile, readdir, stat } from 'fs/promises';
import path from 'path';
import { BasicAgent, AgentMetadata } from './agents/index.js';

const execFileAsync = promisify(execFile);

const GITHUB_RAW = 'https://raw.githubusercontent.com';

export interface ClawHubSkill {
  name: string;
  description: string;
  content: string;
  metadata?: Record<string, unknown>;
  path?: string;
  repo?: string;
}

/**
 * Parse a SKILL.md file from disk into a ClawHubSkill.
 */
export async function parseSkillFile(filePath: string): Promise<ClawHubSkill | null> {
  try {
    const content = await readFile(filePath, 'utf8');
    const frontmatter: Record<string, unknown> = {};
    let name = '';
    let description = '';
    let body = content;

    // Parse YAML frontmatter
    const fmMatch = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/);
    if (fmMatch) {
      for (const line of fmMatch[1].split(/\r?\n/)) {
        const kvMatch = line.match(/^(\w+):\s*(.+)$/);
        if (kvMatch) {
          const [, key, value] = kvMatch;
          frontmatter[key] = value.replace(/^["']|["']$/g, '');
        }
      }
      body = fmMatch[2];
    }

    name = (frontmatter.name as string) ?? '';
    description = (frontmatter.description as string) ?? '';

    // Fallback: extract name from first heading
    if (!name) {
      const headingMatch = content.match(/^#\s+(.+)$/m);
      if (headingMatch) name = headingMatch[1].trim();
    }
    if (!name) {
      name = path.basename(path.dirname(filePath)) || path.basename(filePath, path.extname(filePath));
    }

    // Fallback: first non-heading paragraph as description
    if (!description) {
      for (const para of body.split(/\n\n+/)) {
        const trimmed = para.trim();
        if (trimmed && !trimmed.startsWith('#')) {
          description = trimmed.slice(0, 200);
          break;
        }
      }
    }

    return { name, description, content: body, metadata: frontmatter, path: filePath };
  } catch {
    return null;
  }
}

/**
 * Resolve a user-supplied path to an actual SKILL.md file — either a direct
 * path to one (any case) or a directory containing one, matching the on-disk
 * layout `<skills_dir>/[category/]<skill>/SKILL.md`.
 */
export async function resolveSkillPath(inputPath: string): Promise<string | null> {
  try {
    const st = await stat(inputPath);
    if (st.isFile()) return inputPath;
    if (st.isDirectory()) {
      for (const candidate of ['SKILL.md', 'skill.md']) {
        const found = path.join(inputPath, candidate);
        try {
          const s = await stat(found);
          if (s.isFile()) return found;
        } catch {
          // try next candidate
        }
      }
    }
  } catch {
    // path does not exist
  }
  return null;
}

/** Resolve then parse a SKILL.md path or its containing directory. */
export async function parseSkillPath(inputPath: string): Promise<ClawHubSkill | null> {
  const resolved = await resolveSkillPath(inputPath);
  return resolved ? parseSkillFile(resolved) : null;
}

/**
 * Try to execute a script from a skill's `scripts/` directory. Shared by
 * `ClawHubSkillAgent` and any native, per-skill agent generated by
 * `LearnNewAgent`'s `import_skill` action (see `agents/SkillAgent.ts` and
 * `agents/LearnNewAgent.ts`) so script-execution semantics stay identical
 * regardless of which one runs a given skill.
 */
export async function executeSkillScript(
  scriptsDir: string,
  query: string,
  skillName = '',
): Promise<string | null> {
  let entries: string[];
  try {
    entries = await readdir(scriptsDir);
  } catch {
    return null;
  }

  const runners: Array<[string, string]> = [
    [process.execPath, '.js'],
    ['python3', '.py'],
    ['bash', '.sh'],
  ];

  for (const [interpreter, ext] of runners) {
    const script = entries.find(f => f.endsWith(ext));
    if (!script) continue;
    try {
      const { stdout, stderr } = await execFileAsync(
        interpreter,
        [path.join(scriptsDir, script), query],
        { cwd: path.dirname(scriptsDir), timeout: 30_000 },
      );
      return JSON.stringify({
        status: 'success',
        skill: skillName,
        script,
        output: stdout || stderr,
        return_code: 0,
      });
    } catch (e) {
      const err = e as { stdout?: string; stderr?: string; code?: number };
      return JSON.stringify({
        status: 'error',
        skill: skillName,
        script,
        output: err.stdout || err.stderr || '',
        return_code: err.code ?? 1,
      });
    }
  }

  return null;
}

export class ClawHubSkillAgent extends BasicAgent {
  skill: { name: string; description: string; content?: string; path?: string; repo?: string };
  constructor(skill: { name: string; description: string; content?: string; path?: string; repo?: string }) {
    const metadata: AgentMetadata = {
      name: skill.name,
      description: skill.description,
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'Natural language query or command for the skill' },
          action: { type: 'string', description: 'Specific action to perform (if supported by skill)' },
        },
        required: [],
      },
    };
    super(skill.name, metadata);
    this.skill = skill;
  }

  async perform(kwargs: Record<string, unknown> = {}): Promise<string> {
    const query = (kwargs.query as string) || '';
    const action = (kwargs.action as string) || '';

    if (this.skill.path) {
      const scriptsDir = path.join(path.dirname(this.skill.path), 'scripts');
      try {
        const s = await stat(scriptsDir);
        if (s.isDirectory()) {
          const result = await executeSkillScript(scriptsDir, action || query, this.skill.name);
          if (result) return result;
        }
      } catch {
        // no scripts dir
      }
    }

    let hasScripts = false;
    if (this.skill.path) {
      try {
        const s = await stat(path.join(path.dirname(this.skill.path), 'scripts'));
        hasScripts = s.isDirectory();
      } catch {
        hasScripts = false;
      }
    }

    return JSON.stringify({
      status: 'info',
      skill: this.skill.name,
      description: this.skill.description,
      instructions: (this.skill.content || '').slice(0, 2000),
      message: `Skill '${this.skill.name}' loaded. This skill provides instructions/documentation.`,
      has_scripts: hasScripts,
    });
  }
}

export class ClawHubClient {
  skillsDir: string;
  constructor() { this.skillsDir = ''; }

  async search(query: string): Promise<Array<{ id: string; name: string; description: string; author?: string }>> {
    try {
      const response = await fetch(
        `https://api.github.com/search/repositories?q=${encodeURIComponent(query)}+topic:openrappter-skill&sort=stars`,
        { headers: { Accept: 'application/vnd.github.v3+json' } }
      );
      if (!response.ok) return [];
      const data = (await response.json()) as { items: Array<{ full_name: string; name: string; description: string }> };
      return data.items.map((r) => ({ id: r.full_name, name: r.name, description: r.description ?? '', author: r.full_name.split('/')[0] }));
    } catch {
      return [];
    }
  }

  async install(repo: string): Promise<{ status: string; message: string }> {
    try {
      const res = await fetch(`${GITHUB_RAW}/${repo}/main/skill.json`);
      if (!res.ok) return { status: 'error', message: `No skill.json found in ${repo}` };
      return { status: 'success', message: `Skill found at ${repo}. Use SkillsRegistry.install("${repo}") to install.` };
    } catch {
      return { status: 'error', message: `Failed to reach ${repo}` };
    }
  }

  async listInstalled(): Promise<Array<{ name: string; description?: string }>> { return []; }

  async loadAllSkills(): Promise<ClawHubSkillAgent[]> { return []; }
}

export function getClient(): ClawHubClient { return new ClawHubClient(); }

export async function clawhubSearch(q: string): Promise<string> {
  const client = getClient();
  const results = await client.search(q);
  return JSON.stringify({ status: 'success', query: q, results });
}

export async function clawhubInstall(repo: string): Promise<string> {
  const client = getClient();
  const result = await client.install(repo);
  return JSON.stringify(result);
}

export async function clawhubList(): Promise<string> { return JSON.stringify({ status: 'success', skills: [] }); }
