// Regenerates src/template.js from the canonical RAR template so the app never drifts from it.
import { readFileSync, writeFileSync } from "node:fs";
const src = process.argv[2] || "../RAR/template_agent.py";
const t = readFileSync(src, "utf8");
writeFileSync("src/template.js", "// Generated by build_template.mjs from kody-w/RAR template_agent.py. Do not edit.\nexport const TEMPLATE = " + JSON.stringify(t) + ";\n");
