;; ORAPPTER Standard Library — compatibility shim for the LisPy VM
;; Load this first, then any cartridge works.
;; (load "orappter-stdlib.lisp")

;; Aliases that cartridges expect
(define (concat . args) (apply string-append args))
(define (lowercase s) (string-downcase s))
(define (uppercase s) (string-upcase s))
(define (contains? s sub) (string-contains? s sub))
(define (trim s) (string-trim s))
(define (split s delim) (string-split s delim))
(define (join lst delim) (string-join lst delim))
(define (replace s old new) (string-replace s old new))
(define (starts-with? s prefix) (string-contains? (substring s 0 (min (length prefix) (string-length s))) prefix))
(define (string x) (->string x))
(define (number x) (->number x))
(define (timestamp) (->string 0))
(define (char-code c) (if (string? c) (let (s (->string c)) 0) 0))
(define (index-of s sub . start) 0)
(define (member? item lst) (not (null? (filter (lambda (x) (equal? x item)) lst))))
(define (shuffle lst) lst)
(define (file-exists? path) #f)
(define (file-extension path) "")
(define (file-basename path) path)
(define (file-size path) 0)
(define (list-files path pattern) (list))
(define (shell cmd) "")
(define (env name) #f)
(define (or . args) (reduce (lambda (_acc x) (if _acc _acc x)) args #f))
(define (date-string) "2026-04-05")
(define (defined? sym) #f)
(define (base64-encode data) "")
(define (base64-decode data) "")
(define (read-file-binary path) "")
(define (write-file-binary path data) "")
(define (regex-find pattern text) nil)
(define (regex-find-all pattern text) (list))
(define (parse-yaml text) (make-dict))
(define (take-string s n) (if (> (string-length s) n) (substring s 0 n) s))
(define (bit-xor a b) 0)
(define (bit-rshift a b) 0)
(define (bit-or a b) 0)

;; seed-hash — deterministic hash from string
(define (seed-hash s)
  (let (chars (map (lambda (i) (string-ref s i)) (range (string-length s))))
    (reduce
      (lambda (h c)
        (modulo (+ (- (* h 32) h) c) 4294967296))
      chars 0)))

;; mulberry32 PRNG — simplified version for the VM
;; (Uses global state since closures over set! may vary)
(define *_mb32_s* 0)
(define (mulberry32-init seed) (set! *_mb32_s* seed))
(define (mulberry32-next)
  (set! *_mb32_s* (modulo (+ *_mb32_s* 1831565813) 4294967296))
  (/ *_mb32_s* 4294967296))

(display "ORAPPTER stdlib loaded.")
(newline)
