"""Marketplace packaging for an approved Show-and-Tell plan.

Mirrors ``typescript/src/show-and-tell/marketplace.ts``.

The directory shape -- ``.claude-plugin/marketplace.json``, then
``plugins/<plugin>/.claude-plugin/plugin.json``, then
``plugins/<plugin>/skills/<skill>/SKILL.md`` -- is the layout skill
marketplaces already agree on, so an OpenRappter recording drops into one
without a conversion step. The implementation here is OpenRappter's own and
carries no other project's code, branding, ownership, or endorsement.

Export writes only into a private OpenRappter directory, refuses to escape it,
and refuses to write anything a privacy scan flags.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import Any, Callable, Optional, Sequence

from openrappter.paths import openrappter_path
from openrappter.show_and_tell import (
    SHOW_AND_TELL_MARKETPLACE_SCHEMA,
    _private_directory,
    artifact_contains_sensitive_text,
    has_secret_findings,
    scan_sensitive_payload,
)

MARKETPLACE_ATTRIBUTION = (
    "Generated by OpenRappter Show-and-Tell. The directory layout follows an "
    "open skill marketplace convention. This package is not affiliated with, "
    "owned by, or endorsed by any third party, including Microsoft."
)

NAME_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}$")

#: Phrases that would claim someone else's ownership of a generated export.
FALSE_OWNERSHIP = re.compile(
    r"\b(?:(?:endorsed|owned|certified|maintained|published|approved)\s+by\s+"
    r"(?:microsoft|power\s*cat)|official\s+(?:microsoft|power\s*cat)|"
    r"microsoft\s+corporation)\b",
    re.IGNORECASE,
)


def marketplace_root() -> Path:
    return Path(
        os.environ.get(
            "OPENRAPPTER_MARKETPLACE_DIR", str(openrappter_path("marketplace"))
        )
    ).expanduser().resolve()


def slugify_marketplace_name(value: str, fallback: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (value or "").lower())
    slug = re.sub(r"^-+|-+$", "", slug)[:62]
    slug = re.sub(r"-+$", "", slug)
    return slug if NAME_PATTERN.match(slug) else fallback


def _contained_path(root: Path, *segments: str) -> Path:
    """Refuses any name that could walk out of the export root."""
    for segment in segments:
        if not NAME_PATTERN.match(segment):
            raise ValueError(f"Unsafe marketplace path segment: {segment}")
    candidate = Path(root, *segments).resolve()
    try:
        candidate.relative_to(Path(root).resolve())
    except ValueError as error:
        raise ValueError(
            f"Marketplace path escapes the export root: {candidate}"
        ) from error
    return candidate


def _yaml_string(value: str) -> str:
    return json.dumps(value)


def render_skill_description(plan: dict[str, Any]) -> str:
    """The one-line trigger contract a skill host reads before anything else.

    Keeping USE WHEN / USE FOR / DO NOT USE WHEN in the description is what
    stops a recorded workflow being loaded for a task it never saw.
    """
    use_when = " ".join(plan.get("useWhen", []))
    use_for = "; ".join(plan.get("useFor", []))
    do_not = " ".join(plan.get("doNotUseWhen", []))
    rendered = f"USE WHEN: {use_when} USE FOR: {use_for}. DO NOT USE WHEN: {do_not}"
    return re.sub(r"\s+", " ", rendered).strip()


def render_marketplace_skill(plan: dict[str, Any], skill_name: str) -> str:
    tools: list[str] = []
    for step in plan.get("steps", []):
        tool = step.get("tool")
        if tool and tool not in tools:
            tools.append(tool)
    lines = [
        "---",
        f"name: {skill_name}",
        f"description: {_yaml_string(render_skill_description(plan))}",
        "metadata:",
        f"  source: {_yaml_string('openrappter-show-and-tell')}",
        f"  session: {_yaml_string(plan.get('sessionId', ''))}",
        f"  planRevision: {plan.get('revision', 1)}",
        f"  analysisRevision: {plan.get('analysisRevision', 1)}",
        f"  attribution: {_yaml_string(MARKETPLACE_ATTRIBUTION)}",
    ]
    if tools:
        lines.append("allowed-tools:")
        for tool in tools:
            lines.append(f"  - {_yaml_string(tool)}")
    lines.extend(
        ["---", "", f"# {plan.get('title', '')}", "", "## Goal", "", plan.get("intent", ""), ""]
    )

    lines.extend(["## Use when", ""])
    for entry in plan.get("useWhen", []):
        lines.append(f"- {entry}")
    lines.extend(["", "## Use for", ""])
    for entry in plan.get("useFor", []):
        lines.append(f"- {entry}")
    lines.extend(["", "## Do not use when", ""])
    for entry in plan.get("doNotUseWhen", []):
        lines.append(f"- {entry}")

    lines.extend(["", "## Inputs", ""])
    values = plan.get("values", [])
    if not values:
        lines.append("This workflow took no values from the demonstration.")
    else:
        lines.extend(
            [
                "These came from one demonstration. Substitute them per run; do not "
                "treat them as constants.",
                "",
                "| Placeholder | Meaning | Recorded example |",
                "| --- | --- | --- |",
            ]
        )
        for value in values:
            example = (
                "withheld by privacy scan"
                if value.get("exampleMasked")
                else f"`{value.get('example', '')}`"
            )
            lines.append(
                f"| `{{{{{value['id']}}}}}` | {value.get('label', '')} | {example} |"
            )

    lines.extend(["", "## Procedure", ""])
    for index, step in enumerate(plan.get("steps", [])):
        suffix = "".join(
            [
                f" Prefer `{step['tool']}`." if step.get("tool") else "",
                f" Destination: {step['url']}" if step.get("url") else "",
                (
                    " Ask for confirmation first "
                    f"({', '.join(step.get('riskCategories', []))})."
                )
                if step.get("requiresConfirmation")
                else "",
            ]
        )
        lines.append(f"{index + 1}. **{step.get('title', '')}** — {step.get('detail', '')}{suffix}")

    stats = plan.get("evidenceStats", {})
    lines.extend(
        [
            "",
            "## Execution rules",
            "",
            "- Prefer a native API, CLI, filesystem, or browser tool over replaying "
            "screen coordinates.",
            "- Re-locate controls by meaning, not by recorded pixels.",
            "- Stop and ask before destructive, financial, publishing, or "
            "message-sending steps.",
            "- Never request, persist, or echo credentials from the demonstration.",
            "",
            "## Evidence and limits",
            "",
            f"- Reconstructed from {stats.get('meaningfulEventCount', 0)} recorded "
            f"event(s) in {stats.get('segmentCount', 0)} segment(s).",
            f"- {stats.get('silentEvents', 0)} event(s) had no narration; "
            f"{stats.get('unexplainedFrames', 0)} frame(s) had no label.",
            f"- {stats.get('detourSegments', 0)} segment(s) were treated as detours.",
            "- Raw screenshots were never shared with a model.",
            "",
        ]
    )
    if plan.get("openQuestions"):
        lines.extend(["### Open questions", ""])
        for question in plan["openQuestions"]:
            lines.append(f"- {question}")
        lines.append("")
    lines.extend(["## Provenance", "", f"- {MARKETPLACE_ATTRIBUTION}", ""])
    return "\n".join(lines)


def render_marketplace_manifest(
    plan: dict[str, Any],
    marketplace_name: str,
    plugin_name: str,
    skill_name: str,
    version: str,
) -> str:
    return (
        json.dumps(
            {
                "name": marketplace_name,
                "owner": {
                    "name": "OpenRappter Show-and-Tell",
                    "url": "https://github.com/kody-w/openrappter",
                },
                "metadata": {
                    "description": "Skills recorded locally with OpenRappter "
                    "Show-and-Tell and approved by their author.",
                    "version": version,
                    "attribution": MARKETPLACE_ATTRIBUTION,
                },
                "plugins": [
                    {
                        "name": plugin_name,
                        "source": f"./plugins/{plugin_name}",
                        "description": render_skill_description(plan),
                        "version": version,
                        "author": {"name": "OpenRappter Show-and-Tell"},
                        "keywords": [
                            "openrappter",
                            "show-and-tell",
                            "recorded-workflow",
                        ],
                        "skills": [f"./skills/{skill_name}"],
                    }
                ],
            },
            indent=2,
        )
        + "\n"
    )


def render_plugin_manifest(
    plan: dict[str, Any], plugin_name: str, skill_name: str, version: str
) -> str:
    return (
        json.dumps(
            {
                "name": plugin_name,
                "description": render_skill_description(plan),
                "version": version,
                "author": {"name": "OpenRappter Show-and-Tell"},
                "keywords": ["openrappter", "show-and-tell", "recorded-workflow"],
                "skills": [f"./skills/{skill_name}"],
                "metadata": {
                    "source": "openrappter-show-and-tell",
                    "sessionId": plan.get("sessionId"),
                    "planRevision": plan.get("revision"),
                    "analysisRevision": plan.get("analysisRevision"),
                    "requiresConfirmation": any(
                        step.get("requiresConfirmation")
                        for step in plan.get("steps", [])
                    ),
                    "attribution": MARKETPLACE_ATTRIBUTION,
                },
            },
            indent=2,
        )
        + "\n"
    )


def render_marketplace_export(
    plan: dict[str, Any],
    root: Optional[str] = None,
    marketplace_name: Optional[str] = None,
    plugin_name: Optional[str] = None,
    skill_name: Optional[str] = None,
    version: Optional[str] = None,
) -> dict[str, Any]:
    """Renders the export without touching disk.

    The same shape can then be validated in a test, previewed in a review, or
    written once.
    """
    if not plan.get("approved"):
        raise ValueError("Approve the Show-and-Tell plan before exporting it.")
    export_root = Path(root).expanduser().resolve() if root else marketplace_root()
    fallback = slugify_marketplace_name(
        plan.get("title") or plan.get("intent") or "", "recorded-workflow"
    )
    resolved_marketplace = slugify_marketplace_name(
        marketplace_name or "openrappter-show-and-tell", "openrappter-show-and-tell"
    )
    resolved_plugin = slugify_marketplace_name(plugin_name or fallback, fallback)
    resolved_skill = slugify_marketplace_name(skill_name or fallback, fallback)
    resolved_version = (
        version
        if isinstance(version, str) and re.fullmatch(r"\d+\.\d+\.\d+", version)
        else f"1.0.{max(0, int(plan.get('revision', 1)) - 1)}"
    )

    marketplace_directory = _contained_path(export_root, resolved_marketplace)
    files = [
        {
            "path": str(marketplace_directory / ".claude-plugin" / "marketplace.json"),
            "content": render_marketplace_manifest(
                plan,
                resolved_marketplace,
                resolved_plugin,
                resolved_skill,
                resolved_version,
            ),
        },
        {
            "path": str(
                _contained_path(marketplace_directory, "plugins", resolved_plugin)
                / ".claude-plugin"
                / "plugin.json"
            ),
            "content": render_plugin_manifest(
                plan, resolved_plugin, resolved_skill, resolved_version
            ),
        },
        {
            "path": str(
                _contained_path(
                    marketplace_directory,
                    "plugins",
                    resolved_plugin,
                    "skills",
                    resolved_skill,
                )
                / "SKILL.md"
            ),
            "content": render_marketplace_skill(plan, resolved_skill),
        },
    ]
    return {
        "files": files,
        "root": str(marketplace_directory),
        "marketplaceName": resolved_marketplace,
        "pluginName": resolved_plugin,
        "skillName": resolved_skill,
    }


def marketplace_content_hash(files: Sequence[dict[str, str]]) -> str:
    digest = hashlib.sha256()
    for file in sorted(files, key=lambda entry: entry["path"]):
        digest.update(Path(file["path"]).name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(file["content"].encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def write_marketplace_export(
    plan: dict[str, Any],
    write: Callable[[str, str], None],
    root: Optional[str] = None,
    marketplace_name: Optional[str] = None,
    plugin_name: Optional[str] = None,
    skill_name: Optional[str] = None,
    version: Optional[str] = None,
) -> dict[str, Any]:
    """Writes the export.

    The caller supplies the writer so the atomic, mode-0600 write used
    everywhere else in Show-and-Tell is reused rather than reimplemented here.
    """
    rendered = render_marketplace_export(
        plan, root, marketplace_name, plugin_name, skill_name, version
    )
    for file in rendered["files"]:
        name = Path(file["path"]).name
        findings = scan_sensitive_payload(file["content"], name)
        if has_secret_findings(findings) or artifact_contains_sensitive_text(
            file["content"]
        ):
            raise RuntimeError(f"Privacy scan rejected the generated {name}.")
        if FALSE_OWNERSHIP.search(file["content"]):
            raise RuntimeError(
                f"Refusing to publish {name}: it claims third-party ownership or "
                "endorsement."
            )
    _private_directory(Path(rendered["root"]))
    for file in rendered["files"]:
        _private_directory(Path(file["path"]).parent)
        write(file["path"], file["content"])
    return {
        "schema": SHOW_AND_TELL_MARKETPLACE_SCHEMA,
        "root": rendered["root"],
        "marketplaceName": rendered["marketplaceName"],
        "pluginName": rendered["pluginName"],
        "skillName": rendered["skillName"],
        "files": [file["path"] for file in rendered["files"]],
        "marketplacePath": rendered["files"][0]["path"],
        "pluginPath": rendered["files"][1]["path"],
        "skillPath": rendered["files"][2]["path"],
        "contentHash": marketplace_content_hash(rendered["files"]),
        "attribution": MARKETPLACE_ATTRIBUTION,
    }


def _read_if_present(path: Path) -> Optional[str]:
    if not path.exists() or path.is_symlink() or not path.is_file():
        return None
    return path.read_text(encoding="utf-8")


def validate_marketplace_export(marketplace_directory: str) -> dict[str, Any]:
    """Validates an exported marketplace on disk.

    Layout, manifest shape, name agreement, trigger metadata, privacy, and
    ownership honesty -- each reported as its own named check, so a failure
    says which claim did not hold.
    """
    checks: list[dict[str, Any]] = []

    def add(name: str, ok: bool, detail: str) -> None:
        checks.append({"name": name, "ok": bool(ok), "detail": detail})

    root = Path(marketplace_directory).expanduser().resolve()
    marketplace_file = root / ".claude-plugin" / "marketplace.json"
    marketplace_raw = _read_if_present(marketplace_file)
    add(
        "marketplace-manifest-exists",
        marketplace_raw is not None,
        str(marketplace_file) if marketplace_raw is not None else f"Missing {marketplace_file}",
    )
    if marketplace_raw is None:
        return {"ok": False, "checks": checks}

    try:
        marketplace = json.loads(marketplace_raw)
    except json.JSONDecodeError as error:
        add("marketplace-manifest-json", False, f"marketplace.json is not valid JSON: {error}")
        return {"ok": False, "checks": checks}
    add("marketplace-manifest-json", True, "marketplace.json parses.")

    marketplace_name = marketplace.get("name")
    add(
        "marketplace-name",
        isinstance(marketplace_name, str) and bool(NAME_PATTERN.match(marketplace_name)),
        f'Marketplace name is "{marketplace_name}".'
        if isinstance(marketplace_name, str)
        else "Marketplace name is missing.",
    )

    plugins = marketplace.get("plugins") if isinstance(marketplace.get("plugins"), list) else []
    add("marketplace-plugins", len(plugins) > 0, f"{len(plugins)} plugin entry/entries declared.")

    seen: set[str] = set()
    for entry in plugins:
        plugin = entry if isinstance(entry, dict) else {}
        name = plugin.get("name") if isinstance(plugin.get("name"), str) else ""
        source = plugin.get("source") if isinstance(plugin.get("source"), str) else ""
        add(
            f"plugin-name:{name or '(unnamed)'}",
            bool(NAME_PATTERN.match(name)) and name not in seen,
            f"Duplicate plugin name {name}." if name in seen else f'Plugin name is "{name}".',
        )
        seen.add(name)

        resolved = (root / source).resolve()
        contained = source.startswith("./") and (
            resolved == root or root in resolved.parents
        )
        add(
            f"plugin-source:{name}",
            contained,
            f"Source {source} stays inside the marketplace."
            if contained
            else f"Source {source} escapes the marketplace root.",
        )
        if not contained:
            continue

        plugin_file = resolved / ".claude-plugin" / "plugin.json"
        plugin_raw = _read_if_present(plugin_file)
        add(
            f"plugin-manifest:{name}",
            plugin_raw is not None,
            str(plugin_file) if plugin_raw is not None else f"Missing {plugin_file}",
        )
        if plugin_raw is None:
            continue
        try:
            plugin_json = json.loads(plugin_raw)
        except json.JSONDecodeError as error:
            add(
                f"plugin-manifest-json:{name}",
                False,
                f"plugin.json is not valid JSON: {error}",
            )
            continue
        add(
            f"plugin-manifest-json:{name}",
            plugin_json.get("name") == name,
            "plugin.json name matches the marketplace entry."
            if plugin_json.get("name") == name
            else f"plugin.json name {plugin_json.get('name')} does not match {name}.",
        )

        declared = plugin_json.get("skills") if isinstance(plugin_json.get("skills"), list) else []
        add(f"plugin-skills:{name}", len(declared) > 0, f"{len(declared)} skill(s) declared.")
        for skill_entry in declared:
            relative = skill_entry if isinstance(skill_entry, str) else ""
            skill_directory = (resolved / relative).resolve()
            inside_skills = relative.startswith("./skills/") and (
                skill_directory == resolved or resolved in skill_directory.parents
            )
            add(
                f"skill-path:{relative or '(unnamed)'}",
                inside_skills,
                f"{relative} resolves inside the plugin."
                if inside_skills
                else f"{relative} does not resolve inside the plugin's skills directory.",
            )
            if not inside_skills:
                continue
            skill_file = skill_directory / "SKILL.md"
            skill = _read_if_present(skill_file)
            add(
                f"skill-file:{skill_directory.name}",
                skill is not None,
                str(skill_file) if skill is not None else f"Missing {skill_file}",
            )
            if skill is None:
                continue
            frontmatter_match = re.match(r"^---\n(.*?)\n---", skill, re.DOTALL)
            frontmatter = frontmatter_match.group(1) if frontmatter_match else ""
            name_match = re.search(r"^name:\s*(.+)$", frontmatter, re.MULTILINE)
            declared_name = name_match.group(1).strip() if name_match else None
            add(
                f"skill-frontmatter:{skill_directory.name}",
                declared_name == skill_directory.name,
                f'Frontmatter name is "{declared_name}".'
                if declared_name
                else "SKILL.md has no frontmatter name.",
            )
            description_match = re.search(
                r"^description:\s*(.+)$", frontmatter, re.MULTILINE
            )
            description = description_match.group(1) if description_match else ""
            # "DO NOT USE WHEN:" ends in "USE WHEN:", so a plain substring test
            # reports a description that lost its positive trigger as complete.
            has_triggers = bool(
                re.search(r"(?<!DO NOT )USE WHEN:", description)
                and "USE FOR:" in description
                and "DO NOT USE WHEN:" in description
            )
            add(
                f"skill-triggers:{skill_directory.name}",
                has_triggers,
                "Description declares USE WHEN, USE FOR, and DO NOT USE WHEN."
                if has_triggers
                else "Description is missing USE WHEN, USE FOR, or DO NOT USE WHEN.",
            )
            skill_findings = scan_sensitive_payload(skill, "SKILL.md")
            add(
                f"skill-privacy:{skill_directory.name}",
                not has_secret_findings(skill_findings)
                and not artifact_contains_sensitive_text(skill),
                "Secret-shaped text found: "
                + ", ".join(finding["kind"] for finding in skill_findings)
                if has_secret_findings(skill_findings)
                else "No secret-shaped text.",
            )
            add(
                f"skill-attribution:{skill_directory.name}",
                MARKETPLACE_ATTRIBUTION in skill and not FALSE_OWNERSHIP.search(skill),
                "Attribution present and claims no third-party endorsement."
                if MARKETPLACE_ATTRIBUTION in skill
                else "Attribution is missing or claims third-party ownership.",
            )

    ownership_honest = not FALSE_OWNERSHIP.search(marketplace_raw)
    add(
        "marketplace-ownership",
        ownership_honest,
        "marketplace.json claims no third-party ownership or endorsement."
        if ownership_honest
        else "marketplace.json claims third-party ownership or endorsement.",
    )

    return {"ok": all(check["ok"] for check in checks), "checks": checks}


__all__ = [
    "FALSE_OWNERSHIP",
    "MARKETPLACE_ATTRIBUTION",
    "NAME_PATTERN",
    "marketplace_content_hash",
    "marketplace_root",
    "render_marketplace_export",
    "render_marketplace_manifest",
    "render_marketplace_skill",
    "render_plugin_manifest",
    "render_skill_description",
    "slugify_marketplace_name",
    "validate_marketplace_export",
    "write_marketplace_export",
]
