#!/usr/bin/env python3
"""
rapp_copilot_in_chrome_agent.py -- install, verify, and diagnose the Chrome
browser-automation bridge that lets GitHub Copilot CLI drive real Chrome.

Stdlib only, Python 3.9+. No framework, no install step.

    python3 rapp_copilot_in_chrome_agent.py '{"action": "doctor"}'
    echo '{"action": "install"}' | python3 rapp_copilot_in_chrome_agent.py
    python3 rapp_copilot_in_chrome_agent.py --tool

Companion to SKILL.md, which carries the browser-usage guide. See
https://github.com/kody-w/rapp-copilot-in-chrome
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import time

try:
    from agents.basic_agent import BasicAgent
except ImportError:  # running OUTSIDE the brainstem -- stay executable anyway.
    class BasicAgent:
        def __init__(self, name=None, metadata=None):
            if name:
                self.name = name
            if metadata:
                self.metadata = metadata

        def perform(self, **kwargs):
            return "Not implemented."

        def system_context(self):
            return None

        def to_tool(self):
            return {"type": "function", "function": {
                "name": self.name,
                "description": self.metadata.get("description", ""),
                "parameters": self.metadata.get("parameters", {})}}

__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/rapp_copilot_in_chrome_agent",
    "version": "1.0.0",
    "display_name": "RAPP Copilot in Chrome",
    "description": "Install, verify, and diagnose the Chrome browser-automation bridge for Copilot CLI.",
    "author": "kody-w",
    "tags": ["browser", "chrome", "mcp", "automation", "copilot-cli"],
    "category": "integrations",
    "quality_tier": "official",
    "requires_env": [],
    "example_call": "Check whether rapp-copilot-in-chrome is installed and the browser bridge is healthy.",
}

EXTENSION_ID = "fcoeoabgfenejglbffodgkkbkcdhcgfn"
NATIVE_HOST = "com.anthropic.claude_code_browser_extension"
SERVER_NAME = "rapp-copilot-in-chrome"

HOME = os.path.expanduser("~")
COPILOT_DIR = os.path.join(HOME, ".copilot")
BIN_PATH = os.path.join(COPILOT_DIR, "bin", SERVER_NAME)
MCP_CONFIG = os.path.join(COPILOT_DIR, "mcp-config.json")
SKILL_DIR = os.path.join(COPILOT_DIR, "skills", SERVER_NAME)

LAUNCHER = """#!/bin/sh
# rapp-copilot-in-chrome -- stdio MCP server bridging Copilot CLI to Chrome.
# Generated by rapp_copilot_in_chrome_agent.py
# https://github.com/kody-w/rapp-copilot-in-chrome
set -e

if [ -n "$RAPP_CHROME_CLAUDE_BIN" ] && [ -x "$RAPP_CHROME_CLAUDE_BIN" ]; then
  CLAUDE_BIN="$RAPP_CHROME_CLAUDE_BIN"
elif [ -x "$HOME/.local/bin/claude" ]; then
  CLAUDE_BIN="$HOME/.local/bin/claude"
else
  CLAUDE_BIN="$(command -v claude 2>/dev/null || true)"
fi

if [ -z "$CLAUDE_BIN" ] || [ ! -x "$CLAUDE_BIN" ]; then
  echo "rapp-copilot-in-chrome: cannot locate the 'claude' binary that hosts the browser bridge." >&2
  echo "Install Claude Code, or set RAPP_CHROME_CLAUDE_BIN to its absolute path." >&2
  exit 127
fi

exec "$CLAUDE_BIN" --claude-in-chrome-mcp
"""


def _claude_bin():
    """Resolve the Claude binary that hosts the browser bridge."""
    env = os.environ.get("RAPP_CHROME_CLAUDE_BIN")
    if env and os.access(env, os.X_OK):
        return env
    local = os.path.join(HOME, ".local", "bin", "claude")
    if os.access(local, os.X_OK):
        return local
    return shutil.which("claude")


def _native_host_manifests():
    """Every native-messaging manifest registering the bridge, across Chromium forks."""
    if sys.platform == "darwin":
        root = os.path.join(HOME, "Library", "Application Support")
        bases = {
            "Chrome": ["Google", "Chrome"],
            "Chrome Beta": ["Google", "Chrome Beta"],
            "Chrome Canary": ["Google", "Chrome Canary"],
            "Chromium": ["Chromium"],
            "Brave": ["BraveSoftware", "Brave-Browser"],
            "Edge": ["Microsoft", "Edge"],
        }
    elif sys.platform.startswith("linux"):
        root = os.path.join(HOME, ".config")
        bases = {
            "Chrome": ["google-chrome"],
            "Chromium": ["chromium"],
            "Brave": ["BraveSoftware", "Brave-Browser"],
            "Edge": ["microsoft-edge"],
        }
    else:
        return []

    found = []
    for label, parts in bases.items():
        path = os.path.join(root, *parts, "NativeMessagingHosts", NATIVE_HOST + ".json")
        if os.path.exists(path):
            found.append({"browser": label, "path": path})
    return found


def _extension_installed():
    """True if the extension directory exists in any profile of any Chromium fork."""
    if sys.platform == "darwin":
        roots = [os.path.join(HOME, "Library", "Application Support", "Google", "Chrome"),
                 os.path.join(HOME, "Library", "Application Support", "Chromium"),
                 os.path.join(HOME, "Library", "Application Support", "BraveSoftware",
                              "Brave-Browser")]
    elif sys.platform.startswith("linux"):
        roots = [os.path.join(HOME, ".config", "google-chrome"),
                 os.path.join(HOME, ".config", "chromium"),
                 os.path.join(HOME, ".config", "BraveSoftware", "Brave-Browser")]
    else:
        return False

    for root in roots:
        if not os.path.isdir(root):
            continue
        try:
            for profile in os.listdir(root):
                if os.path.isdir(os.path.join(root, profile, "Extensions", EXTENSION_ID)):
                    return True
        except OSError:
            continue
    return False


def _read_mcp_config(strict=False):
    if not os.path.exists(MCP_CONFIG):
        return {}
    try:
        with open(MCP_CONFIG, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (ValueError, OSError):
        if strict:
            raise ValueError(
                "refusing to overwrite unreadable MCP config: %s" % MCP_CONFIG
            )
        return {}


def _write_mcp_config(cfg):
    """Write config atomically and keep OAuth/server metadata private."""
    os.makedirs(COPILOT_DIR, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        prefix=".mcp-config.",
        suffix=".json",
        dir=COPILOT_DIR,
    )
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(cfg, fh, indent=2)
            fh.write("\n")
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, MCP_CONFIG)
        os.chmod(MCP_CONFIG, 0o600)
    finally:
        try:
            os.remove(tmp)
        except OSError:
            pass


def _probe(timeout=45, live=False):
    """Speak MCP over stdio to the bridge.

    Returns a dict with the tool count and, when live=True, a real round trip
    through Chrome proving tabs are reachable.
    """
    if os.access(BIN_PATH, os.X_OK):
        argv = [BIN_PATH]
    else:
        claude = _claude_bin()
        if not claude:
            return {"ok": False, "error": "no launcher and no claude binary found"}
        argv = [claude, "--claude-in-chrome-mcp"]

    try:
        proc = subprocess.Popen(argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, text=True, bufsize=1)
    except OSError as exc:
        return {"ok": False, "error": "could not start bridge: %s" % exc}

    threading.Thread(target=lambda: [None for _ in proc.stderr], daemon=True).start()

    def send(obj):
        proc.stdin.write(json.dumps(obj) + "\n")
        proc.stdin.flush()

    def wait(msg_id, budget):
        deadline = time.time() + budget
        while time.time() < deadline:
            line = proc.stdout.readline()
            if not line:
                return None
            try:
                msg = json.loads(line)
            except ValueError:
                continue
            if msg.get("id") == msg_id:
                return msg
        return None

    out = {"ok": False}
    try:
        send({"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {
            "protocolVersion": "2025-06-18", "capabilities": {},
            "clientInfo": {"name": "rapp-copilot-in-chrome-doctor", "version": "1.0.0"}}})
        send({"jsonrpc": "2.0", "method": "notifications/initialized"})
        init = wait(1, timeout)
        if not init:
            return {"ok": False, "error": "bridge did not answer initialize"}
        out["server"] = init.get("result", {}).get("serverInfo", {})

        send({"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}})
        listed = wait(2, timeout)
        if not listed:
            return {"ok": False, "error": "bridge did not answer tools/list"}
        tools = listed.get("result", {}).get("tools", [])
        out["tool_count"] = len(tools)
        out["tools"] = sorted(t["name"] for t in tools)
        out["ok"] = True

        if live:
            send({"jsonrpc": "2.0", "id": 3, "method": "tools/call", "params": {
                "name": "tabs_context_mcp", "arguments": {"createIfEmpty": True}}})
            ctx = wait(3, timeout)
            if ctx and not ctx.get("result", {}).get("isError"):
                out["browser_connected"] = True
                out["tab_context"] = ctx["result"]["content"][0].get("text", "")[:400]
            else:
                out["browser_connected"] = False
                out["browser_error"] = "tabs_context_mcp failed; extension may be disconnected"
    finally:
        try:
            proc.kill()
        except OSError:
            pass
    return out


def _do_install(skill_src_dir):
    steps = []

    os.makedirs(os.path.dirname(BIN_PATH), exist_ok=True)
    with open(BIN_PATH, "w", encoding="utf-8") as fh:
        fh.write(LAUNCHER)
    os.chmod(BIN_PATH, 0o755)
    steps.append("wrote launcher %s" % BIN_PATH)

    cfg = _read_mcp_config(strict=True)
    cfg.setdefault("mcpServers", {})[SERVER_NAME] = {
        "type": "local", "command": BIN_PATH, "args": [], "tools": ["*"]}
    _write_mcp_config(cfg)
    steps.append("registered MCP server '%s' in %s" % (SERVER_NAME, MCP_CONFIG))

    if skill_src_dir and os.path.isdir(skill_src_dir):
        copied = []
        os.makedirs(SKILL_DIR, exist_ok=True)
        for name in ("SKILL.md", os.path.basename(os.path.abspath(__file__))):
            src = os.path.join(skill_src_dir, name)
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(SKILL_DIR, name))
                copied.append(name)
        if copied:
            steps.append("installed skill (%s) to %s" % (", ".join(copied), SKILL_DIR))

    return steps


def _do_uninstall():
    steps = []
    cfg = _read_mcp_config(strict=True)
    if cfg.get("mcpServers", {}).pop(SERVER_NAME, None) is not None:
        _write_mcp_config(cfg)
        steps.append("unregistered MCP server '%s'" % SERVER_NAME)
    if os.path.exists(BIN_PATH):
        os.remove(BIN_PATH)
        steps.append("removed launcher %s" % BIN_PATH)
    if os.path.isdir(SKILL_DIR):
        shutil.rmtree(SKILL_DIR)
        steps.append("removed skill %s" % SKILL_DIR)
    return steps or ["nothing to remove; already uninstalled"]


class RappCopilotInChromeAgent(BasicAgent):
    def __init__(self):
        self.name = "RappCopilotInChrome"
        self.metadata = {
            "name": self.name,
            "description": (
                "Install, verify, and diagnose the rapp-copilot-in-chrome browser bridge "
                "that lets GitHub Copilot CLI drive the user's real, logged-in Chrome. "
                "Use when setting it up, when browser tools are missing or failing, or "
                "when the user asks whether the Chrome bridge is working."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "description": (
                            "What to do. 'doctor' (default) runs every check including a "
                            "live round trip through Chrome. 'status' is a fast check with "
                            "no browser traffic. 'install' writes the launcher, registers "
                            "the MCP server, and installs the skill. 'uninstall' removes "
                            "all three."
                        ),
                        "enum": ["doctor", "status", "install", "uninstall"],
                    },
                    "skill_dir": {
                        "type": "string",
                        "description": (
                            "Directory holding SKILL.md to install alongside the server. "
                            "Defaults to the directory containing this file."
                        ),
                    },
                    "timeout": {
                        "type": "integer",
                        "description": "Seconds to wait for the bridge to answer. Default 45.",
                        "minimum": 5,
                        "maximum": 300,
                    },
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        action = (kwargs.get("action") or "doctor").strip().lower()
        if action not in ("doctor", "status", "install", "uninstall"):
            return json.dumps({
                "status": "error",
                "message": "action must be one of: doctor, status, install, uninstall"})

        try:
            timeout = int(kwargs.get("timeout") or 45)
        except (TypeError, ValueError):
            timeout = 45
        timeout = max(5, min(300, timeout))

        skill_dir = kwargs.get("skill_dir") or os.path.dirname(os.path.abspath(__file__))

        if action == "uninstall":
            steps = _do_uninstall()
            return json.dumps({
                "status": "success", "action": "uninstall", "steps": steps,
                "summary": "Uninstalled.\n\n" + "\n".join("- " + s for s in steps)})

        steps = []
        if action == "install":
            try:
                steps = _do_install(skill_dir)
            except (OSError, ValueError) as exc:
                return json.dumps({"status": "error", "message": "install failed: %s" % exc})

        claude = _claude_bin()
        manifests = _native_host_manifests()
        extension = _extension_installed()
        registered = SERVER_NAME in _read_mcp_config().get("mcpServers", {})
        launcher_ok = os.access(BIN_PATH, os.X_OK)

        checks = [
            {"check": "claude binary (hosts the bridge)", "ok": bool(claude),
             "detail": claude or "not found -- install Claude Code or set RAPP_CHROME_CLAUDE_BIN"},
            {"check": "native messaging host manifest", "ok": bool(manifests),
             "detail": ", ".join(m["browser"] for m in manifests) or
                       "not registered -- launch Claude Code once to install it"},
            {"check": "Chrome extension %s" % EXTENSION_ID, "ok": extension,
             "detail": "installed" if extension
                       else "not found -- install the Claude in Chrome extension"},
            {"check": "launcher %s" % BIN_PATH, "ok": launcher_ok,
             "detail": "executable" if launcher_ok else "missing -- run action 'install'"},
            {"check": "MCP server registered", "ok": registered,
             "detail": ("registered in %s" % MCP_CONFIG) if registered
                       else "not registered -- run action 'install'"},
        ]

        probe = {}
        if action in ("doctor", "install"):
            probe = _probe(timeout=timeout, live=True)
            checks.append({
                "check": "bridge answers MCP", "ok": bool(probe.get("ok")),
                "detail": ("%d tools" % probe["tool_count"]) if probe.get("ok")
                          else probe.get("error", "no response")})
            if probe.get("ok"):
                checks.append({
                    "check": "Chrome reachable (live round trip)",
                    "ok": bool(probe.get("browser_connected")),
                    "detail": "tab group reachable" if probe.get("browser_connected")
                              else probe.get("browser_error", "no browser response")})

        healthy = all(c["ok"] for c in checks)
        summary = "\n".join(
            "%s %s -- %s" % ("[ok]" if c["ok"] else "[!!]", c["check"], c["detail"])
            for c in checks)
        if steps:
            summary = "Installed:\n" + "\n".join("- " + s for s in steps) + "\n\n" + summary
        if healthy:
            summary += ("\n\nHealthy. Restart Copilot CLI, then load the tools with a single "
                        "tool search for \"rapp-copilot-in-chrome\".")
        else:
            summary += "\n\nSome checks failed -- see the details above."

        return json.dumps({
            "status": "success" if healthy else "degraded",
            "action": action,
            "steps": steps,
            "checks": checks,
            "tools": probe.get("tools", []),
            "summary": summary,
            "data_slush": {
                "healthy": healthy,
                "tool_count": probe.get("tool_count", 0),
                "browser_connected": probe.get("browser_connected"),
            },
        })


if __name__ == "__main__":
    # Standalone entry point -- no brainstem, no framework, no install.
    #     python3 rapp_copilot_in_chrome_agent.py '{"action": "doctor"}'
    #     echo '{"action": "install"}' | python3 rapp_copilot_in_chrome_agent.py
    #     python3 rapp_copilot_in_chrome_agent.py --tool
    _args = sys.argv[1:]
    if _args and _args[0] == "--tool":
        print(json.dumps(RappCopilotInChromeAgent().to_tool(), indent=2))
    else:
        _raw = _args[0] if _args else (sys.stdin.read().strip() or "{}")
        print(RappCopilotInChromeAgent().perform(**json.loads(_raw)))
