export const IPC = {
  appInfo: 'rapp:app-info',
  catalogStore: 'rapp:catalog-store',
  catalogHub: 'rapp:catalog-hub',
  catalogInstallAgent: 'rapp:catalog-install-agent',
  catalogInstallSkill: 'rapp:catalog-install-skill',
  projectsList: 'rapp:projects-list',
  projectsCreate: 'rapp:projects-create',
  projectsClone: 'rapp:projects-clone',
  projectsReveal: 'rapp:projects-reveal',
  brainstemStatus: 'rapp:brainstem-status',
  brainstemStart: 'rapp:brainstem-start',
  brainstemStop: 'rapp:brainstem-stop',
  brainstemChat: 'rapp:brainstem-chat',
  brainstemLogin: 'rapp:brainstem-login',
  brainstemLoginPoll: 'rapp:brainstem-login-poll',
  brainstemStatusChanged: 'rapp:brainstem-status-changed',
  shellOpenExternal: 'rapp:shell-open-external',
} as const
