"""
ROI and value selling artifact — Builds an executive business value story for a named customer and product — strategic context, 9 use cases, 2x2 prioritization, pain→outcome map, KPIs, transparent ROI model, and call to action — as a 5-7 slide deck and

AGGREGATED ENTRY. The content authority for this capability is the upstream
library; this file is the structured RAR container for it. It carries a
manifest, a version locked to upstream, a content hash, a provenance record and
a public feedback thread — none of which the upstream entry has on its own.

This entry carries the upstream recipe itself, under its licence and with
attribution: the prompt verbatim, the prerequisites, the step-by-step and
the expected output. Toasting made it deterministic — the same call returns
the same recipe every time — and callable from any Brainstem. The upstream
library remains the authority for the recipe and links home for the source.

  Source library : Cowork Cookbook (Sean Galliher and Cowork Cookbook contributors)
  Upstream entry : https://coworkcookbook.com/recipes/roi-and-value-selling-artifact
  Upstream author: Sean Galliher and Cowork Cookbook contributors
  Upstream version: 1.0.0
  Licence        : CC-BY-4.0

Regenerated automatically by scripts/generate_aggregated_agents.py whenever the
upstream record changes, so this file and its source cannot silently diverge.
"""

__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": '@cowork-cookbook/roi_and_value_selling_artifact',
    "version": '3.0.3',
    "display_name": 'ROI and value selling artifact',
    "description": 'Builds an executive business value story for a named customer and product — strategic context, 9 use cases, 2x2 prioritization, pain→outcome map, KPIs, transparent ROI model, and call to action — as a 5-7 slide deck and',
    "author": 'Sean Galliher and Cowork Cookbook contributors',
    "tags": ['industry_solution', 'business_process', 'prompt', 'other', 'prospect_to_quote', 'advanced', 'read_only'],
    "category": 'general',
    "quality_tier": 'community',
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    # Provenance. `content_digest` fingerprints the upstream record; when it
    # moves, this file is regenerated. `--check` fails the build on drift.
    "source": {
        "aggregated": True,
        "source_id": 'cowork-cookbook',
        "source_name": 'Cowork Cookbook',
        "source_url": 'https://coworkcookbook.com/',
        "upstream_slug": 'roi-and-value-selling-artifact',
        "upstream_url": 'https://coworkcookbook.com/recipes/roi-and-value-selling-artifact',
        "upstream_version": '1.0.0',
        "license": 'CC-BY-4.0',
        "license_verified": True,
        "details": {'license_note': "Recipe content is CC BY 4.0 (share and adapt with attribution) and code is MIT. RAR carries each recipe's prompt, prerequisites, steps and expected output verbatim with attribution, so the toasted agent runs the real recipe; bundles and screenshots stay upstream.", 'license_url': 'https://github.com/seangalliher/Coworkcookbook/blob/main/LICENSE', 'repository_url': 'https://github.com/seangalliher/Coworkcookbook', 'taxonomy_url': 'https://coworkcookbook.com/data/taxonomy.json'},
        "content_digest": '75015fd71b3ec292',
    },
    "industry_context": {'deprecated': False, 'difficulty': 'advanced', 'last_verified_on': None, 'mutates_data': False, 'plugin': 'none', 'process_roots': ['prospect-to-quote'], 'process_tags': ['prospect-to-quote/pursue-opportunities/nurture-opportunities-and-finalize-the-sale'], 'recipe_category': 'other', 'recipe_type': 'prompt', 'upstream_path': 'prospect-to-quote/roi-and-value-selling-artifact', 'uses_skills': {'custom': [], 'ootb': ['PowerPoint'], 'plugin': []}, 'verification_status': 'draft'},
    # The platforms the upstream entry targets. First-class and queryable, not
    # buried in prose: this is what lets the registry answer "what can I launch
    # into Copilot Studio / Cowork / Scout", which is the whole reason an
    # agent.py container beats a bare skill entry for cross-platform reach.
    "platforms": ['Microsoft 365 Copilot Cowork'],
}


try:
    from agents.basic_agent import BasicAgent
except ModuleNotFoundError:
    class BasicAgent:
        def __init__(self, name, metadata):
            self.name = name
            self.metadata = metadata


# The toasted capability, generated by @kody-w/skill_toaster_agent. A licensed
# recipe entry carries the upstream recipe verbatim (with attribution) in
# _SPEC["recipe"]; a metadata-only entry carries RAR's own method for that shape
# of work. See the module docstring for which this is.
_SPEC = {'archetype': 'recipe', 'checks': ['Prerequisite: Microsoft 365 Copilot licence with access to Cowork', 'Output matches: A 5-7 slide PowerPoint executive deck and an interactive HTML executive microsite - strategic context, 9 use cases, prioritization matrix, pain → outcome map, KPIs, transparent ROI model, and a workshop → pilot → scale call to action.'], 'confidence': 1.0, 'deliverable': 'A 5-7 slide PowerPoint executive deck and an interactive HTML executive microsite - strategic context, 9 use cases, prioritization matrix, pain → outcome map, KPIs, transparent ROI model, and a workshop → pilot → scale call to action.', 'operations': ['run', 'prompt', 'plan', 'checklist', 'describe'], 'params': {'context': 'Optional. Details the recipe should use — the record, scope, dates or filters it asks for.', 'customer_and_product': 'Customer name, their website, and the product being positioned, plus three use case categories.', 'industry_and_personas': 'Customer industry and the primary persona(s) the story targets.', 'kpis_and_population': 'Confirmed KPIs and the impacted user population.', 'roi_assumptions': 'Fully loaded hourly cost, volume metric, realization factor (default 0.75), license type, and engagement program.', 'strategic_priorities': 'Known strategic priorities or pain points; left blank, they are researched or labeled as hypotheses.'}, 'recipe': {'authors': ['Sean Galliher'], 'business_value': 'Build an executive-level business value story for a customer - use cases, ROI model, and call to action - delivered as a deck and microsite. A 5-7 slide PowerPoint executive deck and an interactive HTML executive microsite - strategic context, 9 use cases, prioritization matrix, pain → outcome map, KPIs, transparent ROI model, and a workshop → pilot → scale call to action.', 'expected_output': 'A 5-7 slide PowerPoint executive deck and an interactive HTML executive microsite - strategic context, 9 use cases, prioritization matrix, pain → outcome map, KPIs, transparent ROI model, and a workshop → pilot → scale call to action.', 'platform': 'Microsoft 365 Copilot Cowork', 'prerequisites': ['Microsoft 365 Copilot licence with access to Cowork'], 'prompt': 'I need to build an executive-level business value story for [Customer Name] that positions [Product] as the right solution to their most pressing business priorities - delivered as a 5-7 slide PowerPoint and an interactive HTML executive microsite. Before you start, ask me these inputs one at a time: Customer website, industry, primary persona(s), known strategic priorities or pain points, confirmed KPIs, impacted user population, fully loaded hourly cost, volume metric, and realization factor (default 0.75 if unknown).\n\nIf any inputs are missing, generate clearly labeled hypotheses - "Hypothesis - validate with customer" - and proceed.\n\nWork through the following seven sections:\n\nCustomer Strategic Context: Pull the top 3 strategic priorities from the customer\'s website, public filings, or earnings calls. Include a one-line priority summary, one direct quote per priority, and the source URL. Skip if already provided.\n\n[Product] Use Cases: Generate 9 high-value use cases aligned to the customer\'s strategy, distributed across [Use Case Category 1], [Use Case Category 2], and [Use Case Category 3]. Present in a table: Category, Use Case Name, Customer-Specific Description, Business Outcome, Primary Metric Impacted, and Strategic Alignment.\n\nPrioritization View: Place all 9 use cases on a 2x2 matrix: Ease of Implementation (x-axis) vs. Business Impact (y-axis). Recommend 2-3 for a pilot and explain why.\n\nPain → Outcome → Solution Map: Build an executive table mapping: Pain/Constraint, Desired Business Outcome, and [Product] Capability that addresses it. Use customer language throughout - not vendor marketing language.\n\nKPIs: If already provided, use them. If not, propose 2-3 per outcome. For each include: Definition, baseline assumption (labeled), and the discovery question needed to validate it with the customer.\n\nROI Model: Build a transparent value model from the inputs collected: time/cost saved per user, annualized value, realization factor applied, estimated investment ([License Type] + pilot services, stated as assumptions), ROI %, and break-even timing. Design so assumptions are editable and changes visually update the ROI and break-even output.\n\nCall to Action: Close with a clear progression: Executive Alignment Workshop → Pilot Engagement (1-3 priority use cases with a measurement plan) → Scale via [Engagement Program].\n\nCite all public sources with quotes and URLs. Ensure all visuals are explicitly described so they can be recreated.', 'steps': ['Open Cowork and start a new task.', 'Paste the prompt from `prompt.md`, replacing anything in square brackets with your own values.', 'Review the plan Cowork proposes before letting it run.', 'Check any drafted email or calendar change before approving it — the prompt holds them for review rather than sending.'], 'tenant_caveat': '', 'verified_against': '', 'what_it_does': 'A 5-7 slide PowerPoint executive deck and an interactive HTML executive microsite - strategic context, 9 use cases, prioritization matrix, pain → outcome map, KPIs, transparent ROI model, and a workshop → pilot → scale call to action.'}, 'refined_by': 'claude-opus-5', 'refinement': {'description': 'Builds an executive business value story for a named customer and product — strategic context, 9 use cases, 2x2 prioritization, pain→outcome map, KPIs, transparent ROI model, and call to action — as a 5-7 slide deck and', 'example_request': 'Build an ROI and value selling deck and microsite for Contoso positioning Copilot to their exec team.', 'inputs': [{'description': 'Customer name, their website, and the product being positioned, plus three use case categories.', 'name': 'customer_and_product'}, {'description': 'Customer industry and the primary persona(s) the story targets.', 'name': 'industry_and_personas'}, {'description': 'Known strategic priorities or pain points; left blank, they are researched or labeled as hypotheses.', 'name': 'strategic_priorities'}, {'description': 'Confirmed KPIs and the impacted user population.', 'name': 'kpis_and_population'}, {'description': 'Fully loaded hourly cost, volume metric, realization factor (default 0.75), license type, and engagement program.', 'name': 'roi_assumptions'}], 'model': 'claude-opus-5', 'when_to_use': 'Call when preparing an ROI or value-selling artifact for a specific customer and product ahead of an executive briefing, pilot pitch, or business case review.'}, 'signals': ['recipe:prompt', 'refined'], 'steps': ['Open Cowork and start a new task.', 'Paste the prompt from `prompt.md`, replacing anything in square brackets with your own values.', 'Review the plan Cowork proposes before letting it run.', 'Check any drafted email or calendar change before approving it — the prompt holds them for review rather than sending.'], 'subject_label': 'context for the recipe', 'verb': 'Run'}


class RoiAndValueSellingArtifact(BasicAgent):
    """Run agent, toasted from an aggregated upstream entry."""

    def __init__(self):
        self.name = 'RoiAndValueSellingArtifact'
        self.metadata = {
            "name": self.name,
            "display_name": __manifest__["display_name"],
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {'context': {'description': 'Optional. Details the recipe should use — the record, scope, dates or filters it asks for.', 'type': 'string'}, 'customer_and_product': {'description': 'Customer name, their website, and the product being positioned, plus three use case categories.', 'type': 'string'}, 'industry_and_personas': {'description': 'Customer industry and the primary persona(s) the story targets.', 'type': 'string'}, 'kpis_and_population': {'description': 'Confirmed KPIs and the impacted user population.', 'type': 'string'}, 'operation': {'description': 'What to do: run, prompt, plan, checklist, describe.', 'enum': ['run', 'prompt', 'plan', 'checklist', 'describe'], 'type': 'string'}, 'roi_assumptions': {'description': 'Fully loaded hourly cost, volume metric, realization factor (default 0.75), license type, and engagement program.', 'type': 'string'}, 'strategic_priorities': {'description': 'Known strategic priorities or pain points; left blank, they are researched or labeled as hypotheses.', 'type': 'string'}},
                "required": ["operation"],
            },
        }
        super().__init__(self.name, self.metadata)

    # ── helpers ─────────────────────────────────────────────────────────

    def _subject(self, kwargs):
        for key in ("subject", "input", "target", "topic"):
            value = str(kwargs.get(key) or "").strip()
            if value:
                return value
        return ""

    def _header(self, subject):
        label = subject or f"<no {_SPEC['subject_label']} supplied>"
        return f"{_SPEC['verb']}: {label}"

    def _context(self, kwargs):
        extras = []
        for key in _SPEC["params"]:
            if key == "subject":
                continue
            value = str(kwargs.get(key) or "").strip()
            if value:
                extras.append(f"{key}: {value}")
        return extras

    def _plan(self, subject, kwargs):
        lines = [self._header(subject)]
        extras = self._context(kwargs)
        if extras:
            lines += ["", "Context:"] + [f"  {e}" for e in extras]
        lines += ["", "Procedure:"]
        lines += [f"  {i}. {step}" for i, step in enumerate(_SPEC["steps"], 1)]
        if not subject:
            lines += [
                "",
                f"Pass subject=\u0022...\u0022 to bind this procedure to a "
                f"specific {_SPEC['subject_label']}.",
            ]
        return lines

    def _checklist(self):
        return ["Acceptance checks:"] + [f"  [ ] {c}" for c in _SPEC["checks"]]

    def _provenance(self):
        src = __manifest__["source"]
        lines = [
            f"{__manifest__['display_name']} (v{__manifest__['version']})",
            "",
            __manifest__["description"],
            "",
            f"Capability shape: {_SPEC['archetype']} "
            f"(confidence {_SPEC['confidence']})",
        ]
        platforms = __manifest__.get("platforms") or []
        if platforms:
            lines.append("Runs on:          " + ", ".join(platforms))
        lines += [
            "",
            f"Indexed from:     {src['source_name']}",
            f"Upstream entry:   {src['upstream_url']}",
            f"Upstream author:  {__manifest__['author']}",
            "",
            "RAR indexes this capability and implements its method; the "
            "upstream library remains the authority for its own instructions. "
            "Open the link above to get those from the source.",
        ]
        return lines

    # ── recipe entries: the upstream recipe, verbatim, deterministic ─────

    def _recipe_context(self, kwargs):
        extras = []
        subject = self._subject(kwargs)
        if subject:
            extras.append(f"subject: {subject}")
        for key in _SPEC["params"]:
            value = str(kwargs.get(key) or "").strip()
            if value:
                extras.append(f"{key}: {value}")
        return extras

    def _recipe_prompt(self, kwargs):
        r = _SPEC["recipe"]
        lines = [r["prompt"]]
        extras = self._recipe_context(kwargs)
        if extras:
            lines += ["", "Context supplied by the caller:"] + [f"- {e}" for e in extras]
        return lines

    def _recipe_attribution(self):
        src = __manifest__["source"]
        r = _SPEC["recipe"]
        who = ", ".join(r.get("authors") or []) or __manifest__["author"]
        return [
            f"Recipe: {__manifest__['display_name']} — by {who}, {src['source_name']} "
            f"({src['license']}). Source: {src['upstream_url']}",
        ]

    def _perform_recipe(self, op, kwargs):
        r = _SPEC["recipe"]
        ref = _SPEC.get("refinement") or {}
        if op == "prompt":
            return "\n".join(self._recipe_prompt(kwargs) + [""] + self._recipe_attribution())
        if op == "plan":
            lines = [f"Steps for {__manifest__['display_name']} on {r['platform']}:"]
            lines += [f"  {i}. {s}" for i, s in enumerate(r["steps"], 1)]
            return "\n".join(lines + [""] + self._recipe_attribution())
        if op == "checklist":
            lines = ["Before you run it:"] + [f"  [ ] {p}" for p in r["prerequisites"]]
            if r.get("expected_output"):
                lines += ["", "Done when:", f"  [ ] {r['expected_output']}"]
            return "\n".join(lines + [""] + self._recipe_attribution())
        if op == "describe":
            lines = self._provenance()
            if ref.get("when_to_use"):
                lines += ["", f"When to use: {ref['when_to_use']}"]
            if ref.get("example_request"):
                lines += [f"Ask for it like: {ref['example_request']}"]
            if ref.get("inputs"):
                lines += ["", "It will ask you for:"] + [f"  - {i['name']}: {i['description']}" for i in ref["inputs"]]
            if r.get("business_value"):
                lines += ["", f"Why it matters: {r['business_value']}"]
            return "\n".join(lines)
        if op == "run":
            lines = [f"{__manifest__['display_name']} — run on {r['platform']}", ""]
            if r.get("what_it_does"):
                lines += [r["what_it_does"], ""]
            lines += [f"Prompt (paste into {r['platform']}):", ""] + self._recipe_prompt(kwargs) + [""]
            lines += ["Procedure:"] + [f"  {i}. {s}" for i, s in enumerate(r["steps"], 1)] + [""]
            lines += ["Acceptance checks:"] + [f"  [ ] {c}" for c in _SPEC["checks"]] + [""]
            lines += [f"Deliverable: {_SPEC['deliverable']}", ""]
            if r.get("tenant_caveat"):
                lines += [f"Verified upstream: {r['tenant_caveat']}", ""]
            return "\n".join(lines + self._recipe_attribution())
        return (
            f"Unknown operation {op!r}. Valid operations: "
            + ", ".join(_SPEC["operations"])
        )

    # ── entry point ─────────────────────────────────────────────────────

    def perform(self, **kwargs):
        """Run the toasted capability. Always returns a string."""
        op = str(kwargs.get("operation") or "run").strip().lower()
        subject = self._subject(kwargs)

        if _SPEC.get("recipe"):
            return self._perform_recipe(op, kwargs)

        if op == "describe":
            return "\n".join(self._provenance())

        if op == "checklist":
            return "\n".join([self._header(subject), ""] + self._checklist())

        if op == "plan":
            return "\n".join(self._plan(subject, kwargs))

        if op == "run":
            lines = self._plan(subject, kwargs)
            lines += [""] + self._checklist()
            lines += ["", f"Deliverable: {_SPEC['deliverable']}"]
            lines += ["", f"Source: {__manifest__['source']['upstream_url']}"]
            return "\n".join(lines)

        return (
            f"Unknown operation {op!r}. Valid operations: "
            + ", ".join(_SPEC["operations"])
        )


if __name__ == "__main__":
    print(RoiAndValueSellingArtifact().perform(operation="run"))
