"""Rebuild the model Hive, its story and its tour from the vendored rapp-hive/2 reference.

    python3 -B tools/build.py           write model/, tour/ (only into missing or identical files)
    python3 -B tools/build.py --check   verify everything committed is exactly what the reference builds

Everything here is SYNTHETIC: fictional people, public test keys, no real data.
"""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "vendor"))

from rapp_hive2 import crossing, hive, lens as lensmod, rapp1, store  # noqa: E402
from rapp_hive2 import model as contoso  # noqa: E402
from rapp_hive2.rapp1 import Refusal  # noqa: E402

TEST_KEY_WARNING = "Synthetic model: fictional people and devices, signed with public test keys that anyone can re-derive. Never use them for real data."


def short(value: str, n: int = 12) -> str:
    return value[:n] + "…"


def evaluate(files: dict[str, bytes]) -> tuple[Any, dict[str, Any]]:
    with tempfile.TemporaryDirectory() as scratch:
        folder = Path(scratch) / "hive"
        store.write_new_tree(folder, files)
        _carried, _records, evaluation, verdict = hive.evaluate_folder(folder)
    return evaluation, verdict


def story(built: dict[str, Any], evaluation: Any, verdict: dict[str, Any]) -> dict[str, Any]:
    crossings = []
    for item in built["crossings"]:
        try:
            result = crossing.cross_to_member(evaluation, item["source"], item["member"])
            crossings.append({**item, "outcome": "crossed", "payload": result["payload"], "not_expressible_in_target": result["not_expressible_in_target"], "dropped_by_forward_lens": result["dropped_by_forward_lens"], "lossless": result["lossless"]})
        except Refusal as error:
            crossings.append({**item, "outcome": "refused", "code": error.code, "reason": error.message})
    return {
        "schema": "rapp-model-hive-story/1",
        "note": "DERIVED for the tour and the page; never authority. Regenerate with tools/build.py. " + TEST_KEY_WARNING,
        "anchor": built["anchor"],
        "state_particle": verdict["state_particle"],
        "people": built["people"],
        "story": built["story"],
        "crossings": crossings,
        "plan_particle": built["plan"]["plan_particle"],
    }


def _name(people: dict[str, Any], rappid: str) -> str:
    return people.get(rappid, {}).get("label", short(rappid, 24))


def tour(built: dict[str, Any], evaluation: Any, verdict: dict[str, Any], told: dict[str, Any]) -> dict[str, str]:
    people = built["people"]
    rooms: dict[str, str] = {}
    contract = lambda reads, does, check: ["", "## Reads", reads, "", "## Does", does, "", "## Writes", "Nothing: this room is generated by `tools/build.py` from the signed frames.", "", "## Human check", check, ""]  # noqa: E731
    rooms["tour/CONTEXT.md"] = "\n".join([
        "# The tour: seven rooms of a model Hive",
        "",
        TEST_KEY_WARNING,
        "",
        "| Room | What you will see |",
        "|---|---|",
        "| [1. Front door](01-front-door.md) | what a model Hive is and how to check it yourself |",
        "| [2. Residents](02-residents.md) | who is in, how they got in, who is waiting |",
        "| [3. Renovation](03-renovation.md) | the move from the current version (rapp-hive/1) to rapp-hive/2 |",
        "| [4. Schemas and lenses](04-schemas-and-lenses.md) | how different app shapes meet in one view |",
        "| [5. Crossings](05-crossings.md) | one person's message, as another person's app would read it |",
        "| [6. Agreement](06-agreement.md) | how devices agree without a master copy |",
        "| [7. Timeline](07-timeline.md) | every signed step, in order |",
        *contract("- `../model/hive/`: the carried Hive (signed frames, identities, objects).", "Explains the model room by room.", "Check the Hive yourself with `python3 -B -m rapp_hive2 status ../model/hive` (from `vendor/`) or open `app/model-hive.html`."),
    ])
    rooms["tour/01-front-door.md"] = "\n".join([
        "# 1. Front door",
        "",
        f"This is **{contoso.NAME}**, a model Hive: like a model home, everything is furnished so you can walk through, but nobody lives here. " + TEST_KEY_WARNING,
        "",
        "A Hive is one portable organism made of sovereign streams. Each person or device writes only its own signed stream. Nothing else is stored as authority: who belongs, which rules apply and what everything means are **derived** from the signed frames, the same way on every device.",
        "",
        f"- Anchor (the Hive's identity): `{built['anchor']}`",
        f"- Derived state today: `{verdict['state_particle']}`",
        f"- Signed frames: {sum(1 for path in built['hive'] if path.startswith('streams/'))}, from {sum(1 for path in built['hive'] if path.startswith('identities/'))} identities",
        "",
        "Check it yourself: `cd vendor && python3 -B -m rapp_hive2 status ../model/hive`, or open `app/model-hive.html` in any browser.",
        *contract("- `../model/hive/HIVE.json` and `../model/hive/objects/`.", "Introduces the model.", "The anchor above must match what you verify."),
    ])
    member_rows = []
    for rappid in verdict["state"]["members"]:
        info = evaluation.members[rappid]
        how = {"founder": "founder (the rapp-hive/1 owner, now steward)", "admitted": "admitted by grants"}[info["how"]]
        if info.get("legacy"):
            how = "joined on the old system; admitted under the first policy's rules"
        member_rows.append(f"| {_name(people, rappid)} | {how} |")
    waiting_rows = []
    for key, request in sorted(evaluation.pending.items()):
        pinned = evaluation._policy(request["pinned"])
        counted = sum(1 for granter in request["grants"] if evaluation._decides(pinned, granter))
        waiting_rows.append(f"| {_name(people, request['requester'])} | {counted} of {pinned['admit']['quorum']} grants{', key confirmed' if evaluation.attested.get(request['requester']) else ''} |")
    decider_refusals = sum(1 for item in verdict["refusals"] if item["code"] == "REFUSE_NOT_DECIDER")
    rooms["tour/02-residents.md"] = "\n".join([
        "# 2. Residents",
        "",
        f"Policy v{evaluation.policy['version']} is active: every member decides, and joining needs {evaluation.policy['admit']['quorum']} grants and a key confirmed by a person.",
        "",
        "| Member | How they got in |",
        "|---|---|",
        *member_rows,
        "",
        "| Waiting | Progress |",
        "|---|---|",
        *waiting_rows,
        "",
        "Emery asked to join on the old system, before the Hive moved to rapp-hive/2. Policy v2 keeps pending requests on the rules they were made under (`keep-pinned`), and under policy v1 only Avery, the steward, decides. "
        f"So Blake's approval did not count ({decider_refusals} grant refused as `REFUSE_NOT_DECIDER`), and Avery's one approval was enough. Nobody overrode anything, and no request was stranded.",
        "",
        f"Frankie's task waits in quarantine ({len(verdict['quarantined'])} message) until Frankie is admitted. It is kept, not deleted. Because Frankie is not a member yet, its extra `invoice` field teaches the Hive nothing.",
        *contract("- `hive2.accept`, `hive2.join`, `hive2.grant` and `hive2.attest` frames.", "Lists members and waiting requests.", "Confirm each key fingerprint with its owner by voice, video or in person before granting."),
    ])
    plan = built["plan"]
    steps = [f"| {_name(people, step['signer'])} | phase {step['phase']} | {', '.join(draft['kind'] for draft in step['drafts'])} |" for step in plan["steps"]]
    rooms["tour/03-renovation.md"] = "\n".join([
        "# 3. Renovation: from the current version to the frontier",
        "",
        "`model/before/` is the house as it stood on the current version: a rapp-hive/1 declaration (one owner, two members) as the first frame of its Mother Hive stream, signed by Avery exactly as rapp-hive/1 requires, two tasks, and Emery's signed request from the old onboarding script. `model/hive/` is the same house after the move.",
        "",
        "1. The migration plan was built from the rapp-hive/1 declaration. It keeps the world, names the one owner as steward founder, and pins a steward policy whose only decider is Avery, so it decides exactly like rapp-hive/1.",
        f"2. Plan particle `{short(plan['plan_particle'], 16)}`. Each identity then signed only its own steps:",
        "",
        "| Who | When | Signed |",
        "|---|---|---|",
        *steps,
        "",
        "3. Nothing was rewritten: every frame in `before/` is in `hive/` byte for byte, and still verifies under rapp-hive/1.",
        "4. Later the steward adopted policy v2 (every member decides; two grants and a confirmed key to join). Requests already waiting kept their rules.",
        "",
        "Run it yourself: `cd vendor && python3 -B -m rapp_hive2 migrate plan-hive1 ../model/before --declaration <hash> --name \"Contoso Model Hive\" --out /tmp/plan.json`. The protocol repository's MIGRATION.md explains Path A (rapp-hive/1), Path B (seeded join requests) and Path C (new Hives).",
        *contract("- `../model/before/` and the migration frames in `../model/hive/`.", "Shows the move to rapp-hive/2.", "Everyone reviews the plan before signing their own steps."),
    ])
    schema_rows = []
    for particle, value in sorted(evaluation.schemas.items(), key=lambda item: item[0]):
        if value.get("kind") != "memory.save" or value["tags"].get("profile") != contoso.TASKS:
            continue
        mapped = [lens_id for lens_id, active in evaluation.active.items() if lensmod.mapping_for(evaluation.lens_objects[active], particle) is not None]
        schema_rows.append(f"| `{short(particle)}` | {value['tags'].get('operation')} | {', '.join(sorted(value['payload']))} | {', '.join(mapped) or 'waiting for a lens'} |")
    lens_rows = []
    for particle in evaluation.history:
        value = evaluation.lens_objects[particle]
        how = "learned automatically (new fields only)" if particle in evaluation.derived else "adopted by the policy's quorum"
        lens_rows.append(f"| {value['id']} v{value['version']} | {how} |")
    rooms["tour/04-schemas-and-lenses.md"] = "\n".join([
        "# 4. Schemas and lenses",
        "",
        "A schema is a message's shape: field names and types, never values. Lenses map schemas into one shared view (`contoso-task`: task_id, title, owner, due). One mapping serves every message of a schema.",
        "",
        "| Schema | Operation | Fields | Mapped by |",
        "|---|---|---|---|",
        *schema_rows,
        "",
        "| Lens version | How it became active |",
        "|---|---|",
        *lens_rows,
        "",
        "- When the laptop app added `priority`, the schema only gained a field, so v2 was learned automatically; `priority` is reported as dropped until someone maps it.",
        "- When the tablet renamed `title` to `summary`, a person had to teach v3. Two peers adopted it, and the laws held: every old task still means the same.",
        "- A careless v4 that rewrote every owner as `team` had two signatures, but the laws refused it. Signatures cannot override meaning.",
        "- Blake's phone started sending reactions: that schema waits for a lens while everything else keeps working.",
        "- Frankie's quarantined task added an `invoice` field. Only members' messages can teach the Hive a new shape, so nothing was learned from it.",
        *contract("- `hive2.adopt` frames, lens and view objects, and every content frame's schema.", "Explains how shapes meet.", "Approve a lens only after checking what it carries and drops."),
    ])
    crossing_blocks = []
    for item in told["crossings"]:
        if item["outcome"] == "crossed":
            detail = f"Crossed. Could not be expressed in the target: {', '.join(item['not_expressible_in_target']) or 'nothing'}. Payload: `{json.dumps(item['payload'], ensure_ascii=False)}`"
        else:
            detail = f"Refused ({item['code']}): {item['reason']}"
        crossing_blocks += [f"### {item['what']}", "", detail, ""]
    rooms["tour/05-crossings.md"] = "\n".join([
        "# 5. Crossings",
        "",
        "To show one person's message in another person's app, the Hive goes forward through the sender's lens into the shared view, then back through the newest lens version that rebuilds the receiver's schema exactly. The result is an unsigned proposal: only the receiver can sign it.",
        "",
        *crossing_blocks,
        "Try it: `cd vendor && python3 -B -m rapp_hive2 cross ../model/hive <8+ hex of a message> avery-laptop`.",
        *contract("- Content frames and every lens version that was ever active.", "Shows crossings between members' schemas.", "A crossing is a proposal; the receiver decides whether to sign it."),
    ])
    manifest_rows = [f"| {_name(people, item['by'])} | {item['verdict']} | {item['position']} | {item['missing_frames']} |" for item in manifest_results(built["hive"])]
    rooms["tour/06-agreement.md"] = "\n".join([
        "# 6. Agreement without a master copy",
        "",
        "Each device signs a manifest: the newest frame it holds from every stream, and the state it derived from them. Anyone can re-derive that state from exactly those frames.",
        "",
        "| Device | Its claim | Position | Frames it had not seen |",
        "|---|---|---|---|",
        *manifest_rows,
        "",
        "Three devices agree. Blake's phone signed while offline: its claim is consistent, just behind. A device that claims a state its frames do not produce is `divergent`, and everyone can see it.",
        *contract("- `hive2.manifest` frames.", "Shows agreement.", "Investigate any divergent manifest before trusting that device's view."),
    ])
    timeline = [f"| {item['utc']} | {people.get(next((r for r, info in people.items() if info['slug'] == item['who']), ''), {}).get('label', item['who'])} | {item['note']} |" for item in built["story"]]
    rooms["tour/07-timeline.md"] = "\n".join([
        "# 7. Timeline",
        "",
        "Every signed step, in the order every engine processes them.",
        "",
        "| When (UTC) | Who | What |",
        "|---|---|---|",
        *timeline,
        *contract("- Every frame in `../model/hive/streams/`.", "Lists the story.", "Times are what signers declared; order is ascending time, then frame hash."),
    ])
    return {path: text.encode("utf-8") for path, text in rooms.items()}


def manifest_results(files: dict[str, bytes]) -> list[dict[str, Any]]:
    with tempfile.TemporaryDirectory() as scratch:
        folder = Path(scratch) / "hive"
        store.write_new_tree(folder, files)
        carried = hive.load(folder)
        records = hive.verify_frames(carried)
        return hive.manifests(carried, records, hive.Evaluation(carried, records, carried.anchor))


def expected() -> dict[str, bytes]:
    built = contoso.build()
    evaluation, verdict = evaluate(built["hive"])
    told = story(built, evaluation, verdict)
    files = {f"model/hive/{path}": data for path, data in built["hive"].items()}
    files.update({f"model/before/{path}": data for path, data in built["before"].items()})
    files["model/STORY.json"] = (json.dumps(told, indent=1, ensure_ascii=False) + "\n").encode("utf-8")
    files.update(tour(built, evaluation, verdict, told))
    return files


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = expected()
    stale = [path for path, data in files.items() if not (ROOT / path).is_file() or (ROOT / path).read_bytes() != data]
    committed = {path.relative_to(ROOT).as_posix() for base in ("model", "tour") for path in (ROOT / base).rglob("*") if path.is_file()}
    extra = sorted(committed - set(files))
    if args.check:
        print(json.dumps({"ok": not stale and not extra, "stale": stale[:20], "extra": extra[:20]}, indent=2))
        return 0 if not stale and not extra else 1
    if extra:
        print(json.dumps({"ok": False, "refusal": "unexpected files; remove them first", "extra": extra}, indent=2))
        return 1
    changed = [path for path in stale if (ROOT / path).exists()]
    if changed:
        print(json.dumps({"ok": False, "refusal": "existing files differ; delete model/ and tour/ to rebuild", "changed": changed[:20]}, indent=2))
        return 1
    store.write_new_tree(ROOT, {path: files[path] for path in stale}, require_empty=False)
    print(json.dumps({"ok": True, "written": len(stale)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
