/**
 * RappterHub / ClawHub commands.
 *
 * The README documents `openrappter rappterhub install author/agent` and
 * `openrappter clawhub install author/skill`. Both are implemented in the
 * Python runtime (`python/openrappter/rappterhub.py`, `clawhub.py`); the
 * TypeScript `src/rappterhub.ts` is a declared stub whose every method returns
 * an empty list or `Not implemented`.
 *
 * The installed launcher (generated by install.sh) execs the TypeScript runtime
 * whenever `typescript/dist/index.js` exists and only falls back to Python when
 * it does not — so on every dual-runtime install these two documented commands
 * reached a CLI that had never heard of them, and commander handed the words to
 * the chat model.
 *
 * Registering the TypeScript stubs would have turned a wrong answer into a
 * confidently empty one. Delegating to the runtime that implements them is the
 * only option that can be right, and when that runtime is absent the command
 * says so and exits nonzero instead of guessing.
 */

import type { Command } from 'commander';
import { spawnSync } from 'child_process';
import { existsSync } from 'fs';
import { homedir } from 'os';
import path from 'path';

const HUBS = ['rappterhub', 'clawhub'] as const;

/** The install root the launcher and installer agree on. */
export function openrappterHome(): string {
  return process.env.OPENRAPPTER_HOME || path.join(homedir(), '.openrappter');
}

export interface PythonRuntime {
  /** Interpreter to run. */
  python: string;
  /** Directory holding the `openrappter` package. */
  cwd: string;
}

/**
 * Locate the Python runtime the installer lays down beside this one.
 *
 * Both halves must be present: an interpreter alone cannot import
 * `openrappter.cli`, and the sources alone cannot run. Reporting "not
 * installed" for a half-install is the truthful answer — a bare `python3` that
 * cannot import the package would fail with a traceback about a module the
 * user never mentioned.
 */
export function findPythonRuntime(home = openrappterHome()): PythonRuntime | null {
  const pyDir = path.join(home, 'python');
  if (!existsSync(path.join(pyDir, 'openrappter', 'cli.py'))) return null;

  const candidates = [
    path.join(home, '.venv', 'bin', 'python'),
    path.join(home, '.venv', 'Scripts', 'python.exe'),
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) return { python: candidate, cwd: pyDir };
  }
  return null;
}

function delegate(hub: string, args: string[]): number {
  const runtime = findPythonRuntime();
  if (!runtime) {
    console.error(
      `${hub} is provided by the Python runtime, which is not installed here.`,
    );
    console.error(
      'Install it with: curl -fsSL https://kody-w.github.io/openrappter/install.sh | bash',
    );
    return 1;
  }

  const result = spawnSync(
    runtime.python,
    ['-m', 'openrappter.cli', hub, ...args],
    { stdio: 'inherit', cwd: runtime.cwd },
  );

  if (result.error) {
    console.error(`Failed to run the Python runtime: ${result.error.message}`);
    return 1;
  }
  // A signalled child has no exit code. Reporting 0 there would call a killed
  // install a successful one.
  if (result.status === null) {
    console.error(`${hub} terminated by signal ${result.signal ?? 'unknown'}`);
    return 1;
  }
  return result.status;
}

export function registerHubCommands(program: Command): void {
  for (const hub of HUBS) {
    const label = hub === 'rappterhub' ? 'RappterHub' : 'ClawHub';
    const noun = hub === 'rappterhub' ? 'agents' : 'skills';
    program
      .command(hub)
      .description(`Manage ${label} ${noun} (runs the Python runtime)`)
      // The subcommand surface belongs to the Python CLI. Parsing it twice
      // would let the two drift, and the copy here would be the one that lies.
      .allowUnknownOption(true)
      .argument('[args...]', `${label} subcommand and arguments`)
      .action((args: string[]) => {
        process.exit(delegate(hub, args ?? []));
      });
  }
}
