/**
 * The agent writer must say what it actually produced.
 *
 * With no model available, `LearnNewAgent` falls back to a scaffold that echoes
 * its input rather than implementing the description. The result JSON reported
 * plain success, so a caller printed "installed X" for an agent that does
 * nothing — "writes the agent live" overstating a template.
 *
 * Two things are covered: the result now distinguishes a scaffold from a real
 * generation, and the writer can be handed a model after construction (the
 * registry builds agents with no arguments, which is why it never had one).
 *
 * Everything above tests the scaffold direction only, which leaves the more
 * dangerous half unproven: nothing checked that the `generated` branch is ever
 * reached. A flag that can only ever read `scaffold` would make the honesty
 * field itself the lie — and that failure is silent, because a provider that is
 * never wired, a response shape that drifts, or a validator that rejects
 * everything all degrade to a scaffold reported as a success. It had already
 * happened once in the Python runtime, which shelled out to `copilot --message`
 * — not a flag the CLI has — and swallowed the failure in a bare `except`.
 *
 * The tests below pin the other direction, and the refusals around it, with a
 * fake provider so they need no model and run in CI. The end-to-end check
 * against a live model cannot run in CI: driven by hand, both runtimes
 * generated a working ISBN-13 check-digit agent that returned 7 for the prefix
 * 978030640615, the published check digit of ISBN 978-0-306-40615-7.
 */

import { describe, expect, it, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { LearnNewAgent } from '../LearnNewAgent.js';
import { BasicAgent } from '../BasicAgent.js';
import type { LLMProvider } from '../../providers/types.js';

let dir = '';
beforeEach(async () => { dir = await mkdtemp(join(tmpdir(), 'learnnew-')); });
afterEach(async () => { await rm(dir, { recursive: true, force: true }); });

describe('LearnNewAgent honesty', () => {
  it('labels a no-model build as a scaffold, not an implementation', async () => {
    const agent = new LearnNewAgent(dir); // no provider
    const res = JSON.parse(
      await agent.execute({ action: 'create', description: 'count words in text' }),
    ) as Record<string, unknown>;
    expect(res.status).toBe('success');
    expect(res.implementation, 'a template must not be reported as generated').toBe('scaffold');
    expect(String(res.note)).toMatch(/echoes its input/i);
  });

  it('still writes a loadable file', async () => {
    const agent = new LearnNewAgent(dir);
    const res = JSON.parse(
      await agent.execute({ action: 'create', description: 'count words' }),
    ) as Record<string, unknown>;
    const src = await readFile(String(res.file_path), 'utf8');
    expect(src).toContain('export function createAgent');
  });

  it('accepts a model after construction', async () => {
    const agent = new LearnNewAgent(dir);
    expect(typeof (agent as unknown as { setProvider?: unknown }).setProvider).toBe('function');
  });
});

/** A provider that answers with whatever the test wants, without a model. */
function fakeProvider(content: string | null, throws = false): LLMProvider {
  return {
    name: 'fake',
    chat: async () => {
      if (throws) throw new Error('provider exploded');
      return { content } as never;
    },
  } as unknown as LLMProvider;
}

const DESC = 'Compute the ISBN-13 check digit for a 12-digit prefix';

const REAL_AGENT = `/** Auto-generated by LearnNewAgent */
export function createAgent(BasicAgent) {
  class IsbnAgent extends BasicAgent {
    constructor() {
      super('Isbn', { name: 'Isbn', description: 'x', parameters: { type: 'object', properties: {}, required: [] } });
    }
    async perform(kwargs) {
      const digits = String(kwargs.query ?? '').replace(/\\D/g, '').slice(0, 12);
      let sum = 0;
      for (let i = 0; i < digits.length; i += 1) sum += Number(digits[i]) * (i % 2 === 0 ? 1 : 3);
      return JSON.stringify({ status: 'success', check_digit: (10 - (sum % 10)) % 10 });
    }
  }
  return IsbnAgent;
}`;

describe('LearnNewAgent — the generated branch is reachable', () => {
  it('labels a real generation generated, and carries no scaffold note', async () => {
    const agent = new LearnNewAgent(dir);
    agent.setProvider(fakeProvider(REAL_AGENT));

    const res = JSON.parse(
      await agent.execute({ action: 'create', description: DESC, name: 'Isbn' }),
    ) as Record<string, unknown>;

    expect(res.implementation).toBe('generated');
    expect(res.note).toBeUndefined();
    expect(agent.lastGenerationWasTemplate).toBe(false);
  });

  it('writes the generated body rather than the echo template', async () => {
    const agent = new LearnNewAgent(dir);
    agent.setProvider(fakeProvider(REAL_AGENT));

    const res = JSON.parse(
      await agent.execute({ action: 'create', description: DESC, name: 'Isbn' }),
    ) as Record<string, unknown>;
    const src = await readFile(String(res.file_path), 'utf8');

    // A flag reading 'generated' proves nothing if the file on disk is still
    // the scaffold.
    expect(src).toContain('check_digit');
    expect(src).not.toContain('Default implementation');
  });

  it('the agent it wrote actually computes — 978030640615 checks to 7', async () => {
    const agent = new LearnNewAgent(dir);
    agent.setProvider(fakeProvider(REAL_AGENT));
    const res = JSON.parse(
      await agent.execute({ action: 'create', description: DESC, name: 'Isbn' }),
    ) as Record<string, unknown>;

    const { createAgent } = (await import(`file://${String(res.file_path)}`)) as {
      createAgent: (base: typeof BasicAgent) => new () => BasicAgent;
    };
    const built = new (createAgent(BasicAgent))();

    // Values the echo scaffold could not produce: the published check digits of
    // ISBN 978-0-306-40615-7 and 978-0-14-300723-4.
    expect(JSON.parse(await built.perform({ query: '978030640615' })).check_digit).toBe(7);
    expect(JSON.parse(await built.perform({ query: '978014300723' })).check_digit).toBe(4);
  });

  it('falls back to a scaffold — and says so — when the provider throws', async () => {
    const agent = new LearnNewAgent(dir);
    agent.setProvider(fakeProvider(null, true));

    const res = JSON.parse(
      await agent.execute({ action: 'create', description: DESC, name: 'Boom' }),
    ) as Record<string, unknown>;

    // A failing provider must degrade to a scaffold labelled as one, never to a
    // scaffold labelled as an implementation.
    expect(res.implementation).toBe('scaffold');
    expect(agent.lastGenerationWasTemplate).toBe(true);
  });

  it('treats a response missing the factory pattern as no generation at all', async () => {
    const agent = new LearnNewAgent(dir);
    agent.setProvider(fakeProvider('here is your agent!  // prose, not a module'));

    const res = JSON.parse(
      await agent.execute({ action: 'create', description: DESC, name: 'Prose' }),
    ) as Record<string, unknown>;

    // Writing this would put a file on disk that cannot hot-load.
    expect(res.implementation).toBe('scaffold');
  });

  it('rejects a module that defines a different class than the one requested', async () => {
    const agent = new LearnNewAgent(dir);
    agent.setProvider(fakeProvider(REAL_AGENT)); // defines IsbnAgent

    const res = JSON.parse(
      await agent.execute({ action: 'create', description: DESC, name: 'Mismatch' }),
    ) as Record<string, unknown>;

    expect(res.implementation).toBe('scaffold');
  });

  it('does not stay stuck on generated once a provider has succeeded', async () => {
    const agent = new LearnNewAgent(dir);
    agent.setProvider(fakeProvider(REAL_AGENT));
    const first = JSON.parse(
      await agent.execute({ action: 'create', description: DESC, name: 'Isbn' }),
    ) as Record<string, unknown>;
    expect(first.implementation).toBe('generated');

    // The flag is instance state, so a later scaffold has to reset it —
    // otherwise one success would make every subsequent scaffold report as an
    // implementation.
    agent.setProvider(null);
    const second = JSON.parse(
      await agent.execute({ action: 'create', description: DESC, name: 'Second' }),
    ) as Record<string, unknown>;
    expect(second.implementation).toBe('scaffold');
    expect(String(second.note)).toMatch(/echoes its input/i);
  });
});
