"""Shared pytest fixtures and helpers for the Bible test suite."""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def iter_committed_files():
    """Yield every file under REPO_ROOT that would be committed.

    Excludes .git, virtualenvs, __pycache__, and the failures-log file
    that is regenerated by sync.
    """
    skip_dirs = {".git", ".venv", "venv", "__pycache__", ".pytest_cache", "node_modules"}
    skip_files = {"_fetch_failures.json"}
    for p in REPO_ROOT.rglob("*"):
        if not p.is_file():
            continue
        if any(part in skip_dirs for part in p.parts):
            continue
        if p.name in skip_files:
            continue
        yield p
